"""Squashed initial schema for ingestion.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create ingestion module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM event_templates LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # ==========================================================================
    # event_templates - Webhook event processing templates
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE event_templates (
            id UUID PRIMARY KEY,
            connector_id VARCHAR(255) NOT NULL,
            event_type VARCHAR(255) NOT NULL,
            text_template TEXT NOT NULL,
            tag_rules JSON NOT NULL DEFAULT '[]',
            issue_detection_rule TEXT,
            tenant_id VARCHAR(255) NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Indexes
    op.execute(
        "CREATE UNIQUE INDEX idx_event_templates_connector_event "
        "ON event_templates (connector_id, event_type)"
    )
    op.execute("CREATE INDEX idx_event_templates_tenant ON event_templates (tenant_id)")
    op.execute("CREATE INDEX idx_event_templates_connector ON event_templates (connector_id)")


def downgrade() -> None:
    """Drop ingestion module tables."""
    op.execute("DROP TABLE IF EXISTS event_templates CASCADE")
