"""create_openapi_tables

Revision ID: 5bed5b682e72
Revises: 
Create Date: 2025-11-16 22:32:13.496346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bed5b682e72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_strategy', sa.String(), nullable=False),
    # Safety Policies (Task 22)
    sa.Column('allowed_methods', postgresql.JSONB(), nullable=False, server_default='["GET", "POST", "PUT", "PATCH", "DELETE"]'),
    sa.Column('blocked_methods', postgresql.JSONB(), nullable=False, server_default='[]'),
    sa.Column('default_safety_level', sa.String(), nullable=False, server_default='safe'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_tenant_id'), 'connector', ['tenant_id'], unique=False)
    op.create_index('ix_connector_tenant_name', 'connector', ['tenant_id', 'name'], unique=False)
    op.create_table('endpoint_descriptor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('path_params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # Activation & Safety (Task 22)
    sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('safety_level', sa.String(), nullable=False, server_default='safe'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, server_default='false'),
    # Enhanced Documentation (Task 22)
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.Column('usage_examples', postgresql.JSONB(), nullable=True),
    # Agent Learning (future)
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('common_errors', postgresql.JSONB(), nullable=True),
    sa.Column('success_patterns', postgresql.JSONB(), nullable=True),
    # Audit Trail (Task 22)
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.Column('last_modified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_endpoint_connector_method_path', 'endpoint_descriptor', ['connector_id', 'method', 'path'], unique=False)
    op.create_index('ix_endpoint_connector_tags', 'endpoint_descriptor', ['connector_id'], unique=False)
    op.create_index('ix_endpoint_enabled', 'endpoint_descriptor', ['connector_id', 'is_enabled'], unique=False)
    op.create_index('ix_endpoint_safety', 'endpoint_descriptor', ['connector_id', 'safety_level'], unique=False)
    op.create_table('openapi_spec',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('spec_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_connector_credential',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('oauth2_refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth2_token_expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_connector', 'user_connector_credential', ['user_id', 'connector_id'], unique=True)
    op.create_index(op.f('ix_user_connector_credential_user_id'), 'user_connector_credential', ['user_id'], unique=False)
    # NOTE: Don't drop workflow tables - they belong to meho_agent service
    # op.drop_index(op.f('ix_workflow_tenant_id'), table_name='workflow')
    # op.drop_index(op.f('ix_workflow_user_id'), table_name='workflow')
    # op.drop_table('workflow')
    # op.drop_index(op.f('ix_workflow_step_workflow_id'), table_name='workflow_step')
    # op.drop_table('workflow_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_step',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], name=op.f('workflow_step_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_step_pkey'))
    )
    op.create_index(op.f('ix_workflow_step_workflow_id'), 'workflow_step', ['workflow_id'], unique=False)
    op.create_table('workflow',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNING', 'WAITING_APPROVAL', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'), autoincrement=False, nullable=False),
    sa.Column('goal', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_step_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_pkey'))
    )
    op.create_index(op.f('ix_workflow_user_id'), 'workflow', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_tenant_id'), 'workflow', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_user_connector_credential_user_id'), table_name='user_connector_credential')
    op.drop_index('ix_user_connector', table_name='user_connector_credential')
    op.drop_table('user_connector_credential')
    op.drop_table('openapi_spec')
    op.drop_index('ix_endpoint_connector_tags', table_name='endpoint_descriptor')
    op.drop_index('ix_endpoint_connector_method_path', table_name='endpoint_descriptor')
    op.drop_table('endpoint_descriptor')
    op.drop_index('ix_connector_tenant_name', table_name='connector')
    op.drop_index(op.f('ix_connector_tenant_id'), table_name='connector')
    op.drop_table('connector')
    # ### end Alembic commands ###

