"""Squashed initial schema for agents.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create agents module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM chat_session LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # ==========================================================================
    # chat_session - Chat session persistence
    # Final state: with visibility, session_mode, trigger_source, timezone-aware
    # ==========================================================================
    op.execute("""
        CREATE TABLE chat_session (
            id UUID PRIMARY KEY,
            tenant_id VARCHAR NOT NULL,
            user_id VARCHAR NOT NULL,
            title VARCHAR,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            visibility VARCHAR(20) NOT NULL DEFAULT 'private',
            created_by_name VARCHAR(255),
            trigger_source VARCHAR(100),
            session_mode VARCHAR(10) NOT NULL DEFAULT 'agent'
        )
    """)
    op.execute("CREATE INDEX ix_chat_session_tenant_id ON chat_session (tenant_id)")
    op.execute("CREATE INDEX ix_chat_session_user_id ON chat_session (user_id)")
    op.execute(
        "CREATE INDEX ix_chat_session_tenant_visibility "
        "ON chat_session (tenant_id, visibility) "
        "WHERE visibility != 'private'"
    )

    # ==========================================================================
    # chat_message - Individual chat messages
    # Final state: with sender_id/sender_name, timezone-aware
    # ==========================================================================
    op.execute("""
        CREATE TABLE chat_message (
            id UUID PRIMARY KEY,
            session_id UUID NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
            role VARCHAR NOT NULL,
            content TEXT NOT NULL,
            message_data JSON,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            sender_id VARCHAR(255),
            sender_name VARCHAR(255)
        )
    """)
    op.execute("CREATE INDEX ix_chat_message_session_id ON chat_message (session_id)")

    # ==========================================================================
    # recipe - Saved Q&A recipes
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE recipe (
            id UUID PRIMARY KEY,
            tenant_id VARCHAR NOT NULL,
            name VARCHAR NOT NULL,
            description TEXT,
            tags JSONB NOT NULL DEFAULT '[]',
            connector_id UUID NOT NULL,
            endpoint_id UUID,
            original_question TEXT NOT NULL,
            parameters JSONB NOT NULL DEFAULT '[]',
            query_template JSONB NOT NULL,
            interpretation_prompt TEXT,
            execution_count INTEGER NOT NULL DEFAULT 0,
            last_executed_at TIMESTAMP WITH TIME ZONE,
            is_public BOOLEAN NOT NULL DEFAULT false,
            created_by VARCHAR,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("CREATE INDEX ix_recipe_tenant_id ON recipe (tenant_id)")
    op.execute("CREATE INDEX ix_recipe_connector_id ON recipe (connector_id)")
    op.execute("CREATE INDEX ix_recipe_endpoint_id ON recipe (endpoint_id)")

    # ==========================================================================
    # recipe_execution - Recipe execution history
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE recipe_execution (
            id UUID PRIMARY KEY,
            recipe_id UUID NOT NULL REFERENCES recipe(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            parameter_values JSONB NOT NULL DEFAULT '{}',
            status VARCHAR NOT NULL DEFAULT 'pending',
            error_message TEXT,
            result_count INTEGER,
            result_summary TEXT,
            aggregates JSONB NOT NULL DEFAULT '{}',
            started_at TIMESTAMP WITH TIME ZONE,
            completed_at TIMESTAMP WITH TIME ZONE,
            duration_ms INTEGER,
            triggered_by VARCHAR
        )
    """)
    op.execute("CREATE INDEX ix_recipe_execution_recipe_id ON recipe_execution (recipe_id)")
    op.execute("CREATE INDEX ix_recipe_execution_tenant_id ON recipe_execution (tenant_id)")

    # ==========================================================================
    # tenant_agent_config - Tenant-specific agent configuration
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE tenant_agent_config (
            id UUID PRIMARY KEY,
            tenant_id VARCHAR NOT NULL UNIQUE,
            display_name VARCHAR(255),
            is_active BOOLEAN NOT NULL DEFAULT true,
            subscription_tier VARCHAR(50) NOT NULL DEFAULT 'free',
            email_domains JSONB DEFAULT '[]',
            max_connectors INTEGER,
            max_knowledge_chunks INTEGER,
            max_workflows_per_day INTEGER,
            installation_context TEXT,
            model_override VARCHAR(100),
            temperature_override JSONB,
            features JSONB NOT NULL DEFAULT '{}',
            updated_by VARCHAR,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute(
        "CREATE INDEX ix_tenant_agent_config_tenant_id ON tenant_agent_config (tenant_id)"
    )
    op.execute(
        "CREATE INDEX ix_tenant_agent_config_is_active ON tenant_agent_config (is_active)"
    )
    op.execute("""
        CREATE INDEX ix_tenant_agent_config_email_domains
        ON tenant_agent_config
        USING GIN (email_domains jsonb_path_ops)
    """)

    # ==========================================================================
    # tenant_agent_config_audit - Config change audit log
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE tenant_agent_config_audit (
            id UUID PRIMARY KEY,
            tenant_id VARCHAR NOT NULL,
            field_changed VARCHAR(100) NOT NULL,
            old_value TEXT,
            new_value TEXT,
            changed_by VARCHAR NOT NULL,
            changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute(
        "CREATE INDEX ix_tenant_agent_config_audit_tenant_id "
        "ON tenant_agent_config_audit (tenant_id)"
    )

    # ==========================================================================
    # approval_request - Pending approval requests
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE approval_request (
            id UUID PRIMARY KEY,
            session_id UUID NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            user_id VARCHAR NOT NULL,
            tool_name VARCHAR(100) NOT NULL,
            tool_args JSONB NOT NULL,
            tool_args_hash VARCHAR(64) NOT NULL,
            danger_level VARCHAR(20) NOT NULL,
            http_method VARCHAR(10),
            endpoint_path VARCHAR(500),
            description TEXT,
            impact_message TEXT,
            user_message TEXT NOT NULL,
            conversation_history JSONB,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            decided_by VARCHAR,
            decided_at TIMESTAMP WITH TIME ZONE,
            decision_reason TEXT,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMP WITH TIME ZONE
        )
    """)
    op.execute("CREATE INDEX ix_approval_request_session_id ON approval_request (session_id)")
    op.execute("CREATE INDEX ix_approval_request_tenant_id ON approval_request (tenant_id)")
    op.execute("CREATE INDEX ix_approval_request_user_id ON approval_request (user_id)")

    # ==========================================================================
    # approval_audit - Approval action audit log
    # Final state: with outcome fields, timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE approval_audit (
            id UUID PRIMARY KEY,
            approval_request_id UUID REFERENCES approval_request(id) ON DELETE SET NULL,
            session_id UUID NOT NULL,
            tenant_id VARCHAR NOT NULL,
            action VARCHAR(50) NOT NULL,
            actor_id VARCHAR,
            tool_name VARCHAR(100) NOT NULL,
            tool_args JSONB,
            danger_level VARCHAR(20),
            http_method VARCHAR(10),
            endpoint_path VARCHAR(500),
            ip_address VARCHAR(45),
            user_agent TEXT,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            outcome_status VARCHAR(20),
            outcome_summary TEXT
        )
    """)
    op.execute("CREATE INDEX ix_approval_audit_session_id ON approval_audit (session_id)")
    op.execute("CREATE INDEX ix_approval_audit_tenant_id ON approval_audit (tenant_id)")
    op.execute("CREATE INDEX ix_approval_audit_created_at ON approval_audit (created_at)")

    # ==========================================================================
    # session_transcripts - Session execution summary
    # Final state: with deleted_at, total_operation_calls (renamed from http_calls),
    # timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE session_transcripts (
            id UUID PRIMARY KEY,
            session_id UUID NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMP WITH TIME ZONE,
            total_llm_calls INTEGER NOT NULL DEFAULT 0,
            total_sql_queries INTEGER NOT NULL DEFAULT 0,
            total_operation_calls INTEGER NOT NULL DEFAULT 0,
            total_tool_calls INTEGER NOT NULL DEFAULT 0,
            total_tokens INTEGER NOT NULL DEFAULT 0,
            total_cost_usd FLOAT,
            total_duration_ms FLOAT NOT NULL DEFAULT 0,
            agent_type VARCHAR(50),
            connector_ids UUID[],
            user_query TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'running',
            deleted_at TIMESTAMP WITH TIME ZONE
        )
    """)
    op.execute(
        "CREATE INDEX ix_session_transcripts_session_id ON session_transcripts (session_id)"
    )
    op.execute(
        "CREATE INDEX ix_session_transcripts_deleted_at ON session_transcripts (deleted_at)"
    )
    op.execute(
        "CREATE INDEX ix_session_transcripts_completed_at ON session_transcripts (completed_at)"
    )

    # ==========================================================================
    # transcript_events - Individual events with full details
    # Final state: timezone-aware timestamp column
    # ==========================================================================
    op.execute("""
        CREATE TABLE transcript_events (
            id UUID PRIMARY KEY,
            transcript_id UUID NOT NULL REFERENCES session_transcripts(id) ON DELETE CASCADE,
            session_id UUID NOT NULL,
            timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            type VARCHAR(50) NOT NULL,
            summary TEXT NOT NULL,
            details JSONB NOT NULL DEFAULT '{}',
            parent_event_id UUID,
            step_number INTEGER,
            node_name VARCHAR(100),
            agent_name VARCHAR(50),
            duration_ms FLOAT
        )
    """)
    op.execute(
        "CREATE INDEX ix_transcript_events_transcript_id ON transcript_events (transcript_id)"
    )
    op.execute(
        "CREATE INDEX ix_transcript_events_session_id ON transcript_events (session_id)"
    )
    op.execute("CREATE INDEX ix_transcript_events_type ON transcript_events (type)")
    op.execute(
        "CREATE INDEX ix_transcript_events_session_timestamp "
        "ON transcript_events (session_id, timestamp)"
    )
    op.execute(
        "CREATE INDEX ix_transcript_events_session_type "
        "ON transcript_events (session_id, type)"
    )
    op.execute("""
        CREATE INDEX ix_transcript_events_details_gin
        ON transcript_events
        USING gin (details jsonb_path_ops)
    """)


def downgrade() -> None:
    """Drop agents module tables."""
    op.execute("DROP TABLE IF EXISTS transcript_events CASCADE")
    op.execute("DROP TABLE IF EXISTS session_transcripts CASCADE")
    op.execute("DROP TABLE IF EXISTS approval_audit CASCADE")
    op.execute("DROP TABLE IF EXISTS approval_request CASCADE")
    op.execute("DROP TABLE IF EXISTS tenant_agent_config_audit CASCADE")
    op.execute("DROP TABLE IF EXISTS tenant_agent_config CASCADE")
    op.execute("DROP TABLE IF EXISTS recipe_execution CASCADE")
    op.execute("DROP TABLE IF EXISTS recipe CASCADE")
    op.execute("DROP TABLE IF EXISTS chat_message CASCADE")
    op.execute("DROP TABLE IF EXISTS chat_session CASCADE")
