"""Squashed initial schema for connectors.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create connectors module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM connector LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # ==========================================================================
    # connector - Core connector configuration
    # Final state: with routing_description, skill fields, automation_enabled,
    # timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE connector (
            id UUID PRIMARY KEY,
            tenant_id VARCHAR NOT NULL,
            name VARCHAR NOT NULL,
            description TEXT,
            base_url VARCHAR NOT NULL,
            connector_type VARCHAR NOT NULL DEFAULT 'rest',
            protocol_config JSONB,
            auth_type VARCHAR NOT NULL,
            auth_config JSONB NOT NULL DEFAULT '{}',
            credential_strategy VARCHAR NOT NULL DEFAULT 'SYSTEM',
            login_url VARCHAR,
            login_method VARCHAR,
            login_config JSONB,
            allowed_methods JSONB NOT NULL DEFAULT '["GET", "POST", "PUT", "PATCH", "DELETE"]',
            blocked_methods JSONB NOT NULL DEFAULT '[]',
            default_safety_level VARCHAR NOT NULL DEFAULT 'safe',
            related_connector_ids JSONB DEFAULT '[]',
            topology_entity_id UUID REFERENCES topology_entities(id) ON DELETE SET NULL,
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            routing_description TEXT,
            skill_name VARCHAR,
            generated_skill TEXT,
            custom_skill TEXT,
            skill_quality_score INTEGER,
            automation_enabled BOOLEAN NOT NULL DEFAULT true
        )
    """)
    op.execute("CREATE INDEX ix_connector_tenant_id ON connector (tenant_id)")
    op.execute("CREATE INDEX ix_connector_tenant_name ON connector (tenant_id, name)")
    op.execute("CREATE INDEX ix_connector_topology_entity_id ON connector (topology_entity_id)")

    # ==========================================================================
    # openapi_spec - OpenAPI specification metadata
    # Final state: timezone-aware created_at
    # ==========================================================================
    op.execute("""
        CREATE TABLE openapi_spec (
            id UUID PRIMARY KEY,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            storage_uri TEXT NOT NULL,
            version VARCHAR,
            spec_version VARCHAR,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # ==========================================================================
    # endpoint_descriptor - REST endpoint descriptors
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE endpoint_descriptor (
            id UUID PRIMARY KEY,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            method VARCHAR NOT NULL,
            path VARCHAR NOT NULL,
            operation_id VARCHAR,
            summary TEXT,
            description TEXT,
            tags JSONB NOT NULL DEFAULT '[]',
            required_params JSONB NOT NULL DEFAULT '[]',
            path_params_schema JSONB NOT NULL DEFAULT '{}',
            query_params_schema JSONB NOT NULL DEFAULT '{}',
            body_schema JSONB NOT NULL DEFAULT '{}',
            response_schema JSONB NOT NULL DEFAULT '{}',
            parameter_metadata JSONB,
            llm_instructions JSONB,
            is_enabled BOOLEAN NOT NULL DEFAULT true,
            safety_level VARCHAR NOT NULL DEFAULT 'safe',
            requires_approval BOOLEAN NOT NULL DEFAULT false,
            custom_description TEXT,
            custom_notes TEXT,
            usage_examples JSONB,
            agent_notes TEXT,
            common_errors JSONB,
            success_patterns JSONB,
            last_modified_by VARCHAR,
            last_modified_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute(
        "CREATE INDEX ix_endpoint_connector_method_path "
        "ON endpoint_descriptor (connector_id, method, path)"
    )
    op.execute("CREATE INDEX ix_endpoint_connector_tags ON endpoint_descriptor (connector_id)")
    op.execute("CREATE INDEX ix_endpoint_enabled ON endpoint_descriptor (connector_id, is_enabled)")
    op.execute(
        "CREATE INDEX ix_endpoint_safety ON endpoint_descriptor (connector_id, safety_level)"
    )

    # ==========================================================================
    # user_connector_credential - User-specific credentials
    # Final state: with credential health columns, timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE user_connector_credential (
            id UUID PRIMARY KEY,
            user_id VARCHAR NOT NULL,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            credential_type VARCHAR NOT NULL,
            encrypted_credentials TEXT NOT NULL,
            oauth2_refresh_token TEXT,
            oauth2_token_expires_at TIMESTAMP WITH TIME ZONE,
            session_token TEXT,
            session_token_expires_at TIMESTAMP WITH TIME ZONE,
            session_refresh_token TEXT,
            session_refresh_expires_at TIMESTAMP WITH TIME ZONE,
            session_state VARCHAR,
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_used_at TIMESTAMP WITH TIME ZONE,
            credential_health VARCHAR(20),
            credential_health_message VARCHAR(500),
            credential_health_checked_at TIMESTAMP WITH TIME ZONE
        )
    """)
    op.execute(
        "CREATE INDEX ix_user_connector_credential_user_id ON user_connector_credential (user_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX ix_user_connector ON user_connector_credential (user_id, connector_id)"
    )

    # ==========================================================================
    # soap_operation_descriptor - SOAP operations from WSDL
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE soap_operation_descriptor (
            id UUID PRIMARY KEY,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            service_name VARCHAR NOT NULL,
            port_name VARCHAR NOT NULL,
            operation_name VARCHAR NOT NULL,
            name VARCHAR NOT NULL,
            description TEXT,
            soap_action VARCHAR,
            namespace VARCHAR,
            style VARCHAR NOT NULL DEFAULT 'document',
            input_schema JSONB NOT NULL DEFAULT '{}',
            output_schema JSONB NOT NULL DEFAULT '{}',
            protocol_details JSONB NOT NULL DEFAULT '{}',
            search_content TEXT,
            is_enabled BOOLEAN NOT NULL DEFAULT true,
            safety_level VARCHAR NOT NULL DEFAULT 'caution',
            requires_approval BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("CREATE INDEX ix_soap_op_connector ON soap_operation_descriptor (connector_id)")
    op.execute(
        "CREATE INDEX ix_soap_op_connector_service "
        "ON soap_operation_descriptor (connector_id, service_name)"
    )
    op.execute(
        "CREATE INDEX ix_soap_op_connector_operation "
        "ON soap_operation_descriptor (connector_id, operation_name)"
    )
    op.execute("CREATE INDEX ix_soap_op_tenant ON soap_operation_descriptor (tenant_id)")

    # ==========================================================================
    # soap_type_descriptor - SOAP type definitions from WSDL
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE soap_type_descriptor (
            id UUID PRIMARY KEY,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            type_name VARCHAR NOT NULL,
            namespace VARCHAR,
            base_type VARCHAR,
            properties JSONB NOT NULL DEFAULT '[]',
            description TEXT,
            search_content TEXT,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("CREATE INDEX ix_soap_type_connector ON soap_type_descriptor (connector_id)")
    op.execute(
        "CREATE INDEX ix_soap_type_connector_name ON soap_type_descriptor (connector_id, type_name)"
    )
    op.execute("CREATE INDEX ix_soap_type_tenant ON soap_type_descriptor (tenant_id)")

    # ==========================================================================
    # connector_operation - Generic typed operations (VMware, K8s, etc.)
    # Final state: with operation inheritance columns, timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE connector_operation (
            id UUID PRIMARY KEY,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            operation_id VARCHAR NOT NULL,
            name VARCHAR NOT NULL,
            description TEXT,
            category VARCHAR,
            parameters JSONB NOT NULL DEFAULT '[]',
            example VARCHAR,
            search_content TEXT,
            is_enabled BOOLEAN NOT NULL DEFAULT true,
            safety_level VARCHAR NOT NULL DEFAULT 'safe',
            requires_approval BOOLEAN NOT NULL DEFAULT false,
            response_entity_type VARCHAR,
            response_identifier_field VARCHAR,
            response_display_name_field VARCHAR,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            source VARCHAR(20) NOT NULL DEFAULT 'type',
            type_operation_id UUID,
            is_enabled_override BOOLEAN
        )
    """)
    op.execute("CREATE INDEX ix_conn_op_connector ON connector_operation (connector_id)")
    op.execute(
        "CREATE INDEX ix_conn_op_connector_operation "
        "ON connector_operation (connector_id, operation_id)"
    )
    op.execute("CREATE INDEX ix_conn_op_tenant ON connector_operation (tenant_id)")
    op.execute("CREATE INDEX ix_conn_op_category ON connector_operation (connector_id, category)")

    # ==========================================================================
    # connector_type - Generic typed entity types (VMware, K8s, etc.)
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE connector_type (
            id UUID PRIMARY KEY,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            type_name VARCHAR NOT NULL,
            description TEXT,
            category VARCHAR,
            properties JSONB NOT NULL DEFAULT '[]',
            search_content TEXT,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("CREATE INDEX ix_conn_type_connector ON connector_type (connector_id)")
    op.execute(
        "CREATE INDEX ix_conn_type_connector_name ON connector_type (connector_id, type_name)"
    )
    op.execute("CREATE INDEX ix_conn_type_tenant ON connector_type (tenant_id)")

    # ==========================================================================
    # email_delivery_log - Email delivery tracking
    # ==========================================================================
    op.execute("""
        CREATE TABLE email_delivery_log (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            from_email VARCHAR NOT NULL,
            to_emails JSONB NOT NULL,
            subject VARCHAR(500) NOT NULL,
            provider_type VARCHAR(20) NOT NULL,
            provider_message_id VARCHAR,
            status VARCHAR(20) NOT NULL,
            error_message TEXT,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("CREATE INDEX ix_email_log_connector ON email_delivery_log (connector_id)")
    op.execute("CREATE INDEX ix_email_log_tenant ON email_delivery_log (tenant_id)")
    op.execute("CREATE INDEX ix_email_log_created ON email_delivery_log (created_at)")

    # ==========================================================================
    # webhook_registration - Per-connector webhook registrations
    # Final state: with require_signature, identity model, notification_targets,
    # timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE webhook_registration (
            id UUID PRIMARY KEY,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            encrypted_secret TEXT NOT NULL,
            prompt_template TEXT NOT NULL,
            rate_limit_per_hour INTEGER NOT NULL DEFAULT 10,
            is_active BOOLEAN NOT NULL DEFAULT true,
            total_events_received INTEGER NOT NULL DEFAULT 0,
            total_events_processed INTEGER NOT NULL DEFAULT 0,
            total_events_deduplicated INTEGER NOT NULL DEFAULT 0,
            last_event_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            require_signature BOOLEAN NOT NULL DEFAULT true,
            created_by_user_id VARCHAR,
            allowed_connector_ids JSONB,
            delegate_credentials BOOLEAN NOT NULL DEFAULT false,
            delegation_active BOOLEAN NOT NULL DEFAULT true,
            notification_targets JSONB
        )
    """)
    op.execute("CREATE INDEX ix_webhook_reg_connector ON webhook_registration (connector_id)")
    op.execute("CREATE INDEX ix_webhook_reg_tenant ON webhook_registration (tenant_id)")
    op.execute(
        "CREATE INDEX ix_webhook_reg_created_by ON webhook_registration (created_by_user_id)"
    )

    # ==========================================================================
    # webhook_event - Webhook event audit log
    # Final state: timezone-aware created_at
    # ==========================================================================
    op.execute("""
        CREATE TABLE webhook_event (
            id UUID PRIMARY KEY,
            webhook_id UUID NOT NULL REFERENCES webhook_registration(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            status VARCHAR(20) NOT NULL,
            payload_hash VARCHAR(64) NOT NULL,
            payload_size_bytes INTEGER NOT NULL,
            session_id UUID,
            error_message TEXT,
            duplicates_suppressed INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("CREATE INDEX ix_webhook_event_webhook ON webhook_event (webhook_id)")
    op.execute("CREATE INDEX ix_webhook_event_created ON webhook_event (created_at)")


def downgrade() -> None:
    """Drop connectors module tables."""
    op.execute("DROP TABLE IF EXISTS webhook_event CASCADE")
    op.execute("DROP TABLE IF EXISTS webhook_registration CASCADE")
    op.execute("DROP TABLE IF EXISTS email_delivery_log CASCADE")
    op.execute("DROP TABLE IF EXISTS connector_type CASCADE")
    op.execute("DROP TABLE IF EXISTS connector_operation CASCADE")
    op.execute("DROP TABLE IF EXISTS soap_type_descriptor CASCADE")
    op.execute("DROP TABLE IF EXISTS soap_operation_descriptor CASCADE")
    op.execute("DROP TABLE IF EXISTS user_connector_credential CASCADE")
    op.execute("DROP TABLE IF EXISTS endpoint_descriptor CASCADE")
    op.execute("DROP TABLE IF EXISTS openapi_spec CASCADE")
    op.execute("DROP TABLE IF EXISTS connector CASCADE")
