"""Squashed initial schema for scheduled_tasks.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create scheduled_tasks module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM scheduled_task LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # ==========================================================================
    # scheduled_task - Cron-based task definitions
    # Final state: with identity model columns (created_by_user_id, delegation),
    # notification_targets, timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE scheduled_task (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id VARCHAR NOT NULL,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            cron_expression VARCHAR(100) NOT NULL,
            timezone VARCHAR(50) NOT NULL,
            prompt TEXT NOT NULL,
            is_enabled BOOLEAN NOT NULL DEFAULT true,
            next_run_at TIMESTAMP WITH TIME ZONE,
            total_runs INTEGER NOT NULL DEFAULT 0,
            last_run_at TIMESTAMP WITH TIME ZONE,
            last_run_status VARCHAR(20),
            created_by_user_id VARCHAR(255),
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            allowed_connector_ids JSONB,
            delegate_credentials BOOLEAN NOT NULL DEFAULT false,
            delegation_active BOOLEAN NOT NULL DEFAULT true,
            notification_targets JSONB
        )
    """)
    op.execute("CREATE INDEX ix_scheduled_task_tenant ON scheduled_task (tenant_id)")
    op.execute("CREATE INDEX ix_scheduled_task_enabled ON scheduled_task (is_enabled)")
    op.execute("CREATE INDEX ix_scheduled_task_created_by ON scheduled_task (created_by_user_id)")

    # ==========================================================================
    # scheduled_task_run - Execution history
    # ==========================================================================
    op.execute("""
        CREATE TABLE scheduled_task_run (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            task_id UUID NOT NULL REFERENCES scheduled_task(id) ON DELETE CASCADE,
            tenant_id VARCHAR NOT NULL,
            status VARCHAR(20) NOT NULL,
            session_id UUID,
            error_message TEXT,
            prompt_snapshot TEXT NOT NULL,
            started_at TIMESTAMP WITH TIME ZONE NOT NULL,
            completed_at TIMESTAMP WITH TIME ZONE,
            duration_seconds INTEGER
        )
    """)
    op.execute("CREATE INDEX ix_sched_run_task ON scheduled_task_run (task_id)")
    op.execute("CREATE INDEX ix_sched_run_tenant ON scheduled_task_run (tenant_id)")
    op.execute("CREATE INDEX ix_sched_run_started ON scheduled_task_run (started_at)")


def downgrade() -> None:
    """Drop scheduled_tasks module tables."""
    op.execute("DROP TABLE IF EXISTS scheduled_task_run CASCADE")
    op.execute("DROP TABLE IF EXISTS scheduled_task CASCADE")
