"""Squashed initial schema for memory.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create memory module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM connector_memory LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # Enable pgvector extension for vector similarity search
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ==========================================================================
    # connector_memory - Connector-scoped memories with confidence & provenance
    # Final state: 1024D Voyage AI embeddings, timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE connector_memory (
            id UUID PRIMARY KEY,
            tenant_id VARCHAR NOT NULL,
            connector_id UUID NOT NULL REFERENCES connector(id) ON DELETE CASCADE,
            title VARCHAR(500) NOT NULL,
            body TEXT NOT NULL,
            memory_type VARCHAR(50) NOT NULL,
            tags JSONB NOT NULL DEFAULT '[]',
            confidence_level VARCHAR(50) NOT NULL DEFAULT 'auto_extracted',
            source_type VARCHAR(50) NOT NULL DEFAULT 'extraction',
            created_by VARCHAR,
            provenance_trail JSONB NOT NULL DEFAULT '[]',
            occurrence_count INTEGER NOT NULL DEFAULT 1,
            last_accessed TIMESTAMP WITH TIME ZONE,
            last_seen TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            embedding vector(1024)
        )
    """)

    # Scalar indexes
    op.execute("CREATE INDEX ix_connector_memory_tenant_id ON connector_memory (tenant_id)")
    op.execute("CREATE INDEX ix_connector_memory_connector_id ON connector_memory (connector_id)")
    op.execute("CREATE INDEX ix_connector_memory_memory_type ON connector_memory (memory_type)")
    op.execute("CREATE INDEX ix_connector_memory_confidence ON connector_memory (confidence_level)")

    # Composite indexes
    op.execute(
        "CREATE INDEX ix_connector_memory_tenant_connector "
        "ON connector_memory (tenant_id, connector_id)"
    )
    op.execute(
        "CREATE INDEX ix_connector_memory_connector_type "
        "ON connector_memory (connector_id, memory_type)"
    )

    # HNSW index for fast vector similarity search
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_connector_memory_embedding_hnsw
        ON connector_memory
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)


def downgrade() -> None:
    """Drop memory module tables."""
    op.execute("DROP TABLE IF EXISTS connector_memory CASCADE")
