"""Squashed initial schema for audit.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create audit module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM audit_event LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # ==========================================================================
    # audit_event - Audit event log
    # Already had timezone-aware timestamps from initial creation
    # ==========================================================================
    op.execute("""
        CREATE TABLE audit_event (
            id UUID PRIMARY KEY NOT NULL,
            tenant_id VARCHAR NOT NULL,
            user_id VARCHAR NOT NULL,
            user_email VARCHAR,
            event_type VARCHAR(50) NOT NULL,
            action VARCHAR(50) NOT NULL,
            resource_type VARCHAR(50) NOT NULL,
            resource_id VARCHAR,
            resource_name VARCHAR,
            details JSONB,
            result VARCHAR(20) NOT NULL DEFAULT 'success',
            ip_address VARCHAR(45),
            user_agent VARCHAR,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Composite indexes for common query patterns
    op.execute("CREATE INDEX ix_audit_event_tenant_created ON audit_event (tenant_id, created_at)")
    op.execute("CREATE INDEX ix_audit_event_user_created ON audit_event (user_id, created_at)")
    op.execute("CREATE INDEX ix_audit_event_type ON audit_event (event_type)")


def downgrade() -> None:
    """Drop audit module tables."""
    op.execute("DROP TABLE IF EXISTS audit_event CASCADE")
