# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 evoila Group
"""
VMware Operation Definitions - Split by Category

These are registered in the generic connector_operation table
so the agent can discover them via search_operations.
"""

from meho_app.modules.connectors.base import OperationDefinition

# COMPUTE OPERATIONS

COMPUTE_OPERATIONS = [
    OperationDefinition(
        operation_id="list_virtual_machines",
        name="List Virtual Machines",
        description="Get all VMs in vCenter. Returns comprehensive data: name, runtime (power state, host, connection state, boot time), config (CPU, memory, guest OS, UUID), guest info (IP, hostname, tools status), stats (CPU/memory usage, uptime), resource pool, datastores, and networks.",
        category="compute",
        parameters=[],
        example="list_virtual_machines()",
        response_entity_type="VirtualMachine",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="get_virtual_machine",
        name="Get Virtual Machine Details",
        description="Get comprehensive details about a specific VM: runtime (power state, host, connection state, boot time), config (CPU, memory, guest OS, UUID, instance UUID), guest info (IP, hostname, tools status/version, guest state), stats (CPU/memory usage, uptime), resource pool, datastores, and networks.",
        category="compute",
        parameters=[
            {"name": "vm_name", "type": "string", "required": True, "description": "Name of the VM"}
        ],
        example="get_virtual_machine(vm_name='my-vm')",
        response_entity_type="VirtualMachine",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="power_on_vm",
        name="Power On VM",
        description="Power on a virtual machine. Returns task ID for tracking.",
        category="compute",
        parameters=[
            {"name": "vm_name", "type": "string", "required": True, "description": "Name of the VM"}
        ],
        example="power_on_vm(vm_name='my-vm')",
    ),
    OperationDefinition(
        operation_id="power_off_vm",
        name="Power Off VM",
        description="Power off a virtual machine (hard power off). Returns task ID.",
        category="compute",
        parameters=[
            {"name": "vm_name", "type": "string", "required": True, "description": "Name of the VM"}
        ],
        example="power_off_vm(vm_name='my-vm')",
    ),
    OperationDefinition(
        operation_id="shutdown_guest",
        name="Shutdown Guest OS",
        description="Gracefully shutdown the guest operating system. Requires VMware Tools.",
        category="compute",
        parameters=[
            {"name": "vm_name", "type": "string", "required": True, "description": "Name of the VM"}
        ],
        example="shutdown_guest(vm_name='my-vm')",
    ),
    OperationDefinition(
        operation_id="list_clusters",
        name="List Clusters",
        description="Get all clusters in vCenter. Returns name, host count, DRS/HA status.",
        category="compute",
        parameters=[],
        example="list_clusters()",
        response_entity_type="Cluster",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="get_cluster",
        name="Get Cluster Details",
        description="Get detailed info about a cluster including DRS and HA config.",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            }
        ],
        example="get_cluster(cluster_name='Production')",
        response_entity_type="Cluster",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="get_drs_recommendations",
        name="Get DRS Recommendations",
        description="Get pending DRS recommendations for a cluster. DRS suggests VM migrations for load balancing.",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            }
        ],
        example="get_drs_recommendations(cluster_name='Production')",
        response_entity_type="DRSRecommendation",
        response_identifier_field="key",
        response_display_name_field="reason",
    ),
    OperationDefinition(
        operation_id="apply_drs_recommendation",
        name="Apply DRS Recommendation",
        description="Apply a DRS recommendation to migrate VMs. Requires recommendation key from get_drs_recommendations.",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
            {
                "name": "recommendation_key",
                "type": "string",
                "required": True,
                "description": "Recommendation key to apply",
            },
        ],
        example="apply_drs_recommendation(cluster_name='Production', recommendation_key='rec-1')",
    ),
    OperationDefinition(
        operation_id="list_hosts",
        name="List ESXi Hosts",
        description="Get all ESXi hosts in vCenter. Returns comprehensive data: name, runtime (connection state, power state, maintenance mode, standby mode, boot time), hardware (vendor, model, UUID, CPU MHz/cores/threads, memory), stats (CPU/memory usage, uptime), parent cluster, VMs list, datastores list, and networks list.",
        category="compute",
        parameters=[],
        example="list_hosts()",
        response_entity_type="HostSystem",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="get_host",
        name="Get Host Details",
        description="Get comprehensive details about an ESXi host: runtime (connection state, power state, maintenance mode, standby mode, boot time), hardware (vendor, model, UUID, CPU MHz/cores/threads, memory), stats (CPU/memory usage, uptime), parent cluster, VMs list, datastores list, and networks list.",
        category="compute",
        parameters=[
            {"name": "host_name", "type": "string", "required": True, "description": "Name of host"}
        ],
        example="get_host(host_name='esxi-01.example.com')",
        response_entity_type="HostSystem",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="list_resource_pools",
        name="List Resource Pools",
        description="Get all resource pools in vCenter.",
        category="compute",
        parameters=[],
        example="list_resource_pools()",
        response_entity_type="ResourcePool",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="create_snapshot",
        name="Create VM Snapshot",
        description="Create a snapshot of a virtual machine. Captures current state including memory (optional).",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "snapshot_name",
                "type": "string",
                "required": True,
                "description": "Name for the snapshot",
            },
            {
                "name": "description",
                "type": "string",
                "required": False,
                "description": "Snapshot description",
            },
            {
                "name": "include_memory",
                "type": "boolean",
                "required": False,
                "description": "Include VM memory state (default: False)",
            },
            {
                "name": "quiesce_guest",
                "type": "boolean",
                "required": False,
                "description": "Quiesce guest filesystem (default: True)",
            },
        ],
        example="create_snapshot(vm_name='web-01', snapshot_name='pre-upgrade', description='Before patch')",
    ),
    OperationDefinition(
        operation_id="list_snapshots",
        name="List VM Snapshots",
        description="Get all snapshots for a virtual machine with creation time and description.",
        category="compute",
        parameters=[
            {"name": "vm_name", "type": "string", "required": True, "description": "Name of the VM"}
        ],
        example="list_snapshots(vm_name='web-01')",
        response_entity_type="Snapshot",
        response_identifier_field="id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="revert_snapshot",
        name="Revert to Snapshot",
        description="Revert a virtual machine to a previous snapshot state. pyvmomi: RevertToSnapshot_Task(host, suppressPowerOn)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "snapshot_name",
                "type": "string",
                "required": True,
                "description": "Name of snapshot to revert to",
            },
            {
                "name": "target_host",
                "type": "string",
                "required": False,
                "description": "Target host for the reverted VM (optional)",
            },
            {
                "name": "suppress_power_on",
                "type": "boolean",
                "required": False,
                "description": "Prevent VM from powering on after revert (default: False)",
            },
        ],
        example="revert_snapshot(vm_name='web-01', snapshot_name='pre-upgrade')",
    ),
    OperationDefinition(
        operation_id="delete_snapshot",
        name="Delete VM Snapshot",
        description="Delete a snapshot from a virtual machine. pyvmomi: RemoveSnapshot_Task(removeChildren, consolidate)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "snapshot_name",
                "type": "string",
                "required": True,
                "description": "Name of snapshot to delete",
            },
            {
                "name": "remove_children",
                "type": "boolean",
                "required": False,
                "description": "Also remove child snapshots (default: False)",
            },
            {
                "name": "consolidate",
                "type": "boolean",
                "required": False,
                "description": "Consolidate disks after removal (default: True)",
            },
        ],
        example="delete_snapshot(vm_name='web-01', snapshot_name='pre-upgrade')",
    ),
    OperationDefinition(
        operation_id="delete_all_snapshots",
        name="Delete All VM Snapshots",
        description="Delete all snapshots from a virtual machine. pyvmomi: RemoveAllSnapshots_Task(consolidate, spec)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "consolidate",
                "type": "boolean",
                "required": False,
                "description": "Consolidate disks after removal (default: True)",
            },
        ],
        example="delete_all_snapshots(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="reconfigure_vm_cpu",
        name="Reconfigure VM CPU",
        description="Change the number of CPUs for a virtual machine. VM may need to be powered off.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "num_cpus",
                "type": "integer",
                "required": True,
                "description": "Number of virtual CPUs",
            },
            {
                "name": "cores_per_socket",
                "type": "integer",
                "required": False,
                "description": "Cores per socket (default: 1)",
            },
        ],
        example="reconfigure_vm_cpu(vm_name='web-01', num_cpus=4)",
    ),
    OperationDefinition(
        operation_id="reconfigure_vm_memory",
        name="Reconfigure VM Memory",
        description="Change the memory size for a virtual machine. VM may need to be powered off.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "memory_mb",
                "type": "integer",
                "required": True,
                "description": "Memory size in MB",
            },
        ],
        example="reconfigure_vm_memory(vm_name='web-01', memory_mb=8192)",
    ),
    OperationDefinition(
        operation_id="rename_vm",
        name="Rename Virtual Machine",
        description="Rename a virtual machine in vCenter inventory.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Current name of the VM",
            },
            {
                "name": "new_name",
                "type": "string",
                "required": True,
                "description": "New name for the VM",
            },
        ],
        example="rename_vm(vm_name='old-name', new_name='new-name')",
    ),
    OperationDefinition(
        operation_id="set_vm_annotation",
        name="Set VM Annotation",
        description="Set or update the annotation (notes) for a virtual machine.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "annotation",
                "type": "string",
                "required": True,
                "description": "Annotation text",
            },
        ],
        example="set_vm_annotation(vm_name='web-01', annotation='Production web server')",
    ),
    OperationDefinition(
        operation_id="migrate_vm",
        name="Migrate VM (vMotion)",
        description="Live migrate a VM to a different host. pyvmomi: MigrateVM_Task(pool, host, priority, state)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "target_host",
                "type": "string",
                "required": True,
                "description": "Target ESXi host name",
            },
            {
                "name": "priority",
                "type": "string",
                "required": False,
                "description": "Migration priority: default, high, low (default: default)",
            },
        ],
        example="migrate_vm(vm_name='web-01', target_host='esxi-02.example.com')",
    ),
    OperationDefinition(
        operation_id="clone_vm",
        name="Clone Virtual Machine",
        description="Create a clone of a virtual machine. Can clone to different datastore/host.",
        category="compute",
        parameters=[
            {
                "name": "source_vm",
                "type": "string",
                "required": True,
                "description": "Name of source VM",
            },
            {
                "name": "clone_name",
                "type": "string",
                "required": True,
                "description": "Name for the clone",
            },
            {
                "name": "target_datastore",
                "type": "string",
                "required": False,
                "description": "Target datastore",
            },
            {
                "name": "target_folder",
                "type": "string",
                "required": False,
                "description": "Target folder",
            },
            {
                "name": "power_on",
                "type": "boolean",
                "required": False,
                "description": "Power on after clone (default: False)",
            },
        ],
        example="clone_vm(source_vm='template-vm', clone_name='new-web-01')",
    ),
    OperationDefinition(
        operation_id="enter_maintenance_mode",
        name="Enter Maintenance Mode",
        description="Put an ESXi host into maintenance mode. VMs will be migrated if DRS is enabled.",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "evacuate_vms",
                "type": "boolean",
                "required": False,
                "description": "Evacuate powered-on VMs (default: True)",
            },
            {
                "name": "timeout",
                "type": "integer",
                "required": False,
                "description": "Timeout in seconds (default: 0 = no timeout)",
            },
        ],
        example="enter_maintenance_mode(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="exit_maintenance_mode",
        name="Exit Maintenance Mode",
        description="Take an ESXi host out of maintenance mode.",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "timeout",
                "type": "integer",
                "required": False,
                "description": "Timeout in seconds (default: 0)",
            },
        ],
        example="exit_maintenance_mode(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="get_host_vms",
        name="Get VMs on Host",
        description="List all VMs running on a specific ESXi host.",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            }
        ],
        example="get_host_vms(host_name='esxi-01.example.com')",
        response_entity_type="VirtualMachine",
        response_identifier_field="moref_id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="reboot_guest",
        name="Reboot Guest OS",
        description="Gracefully reboot the guest operating system. Requires VMware Tools. pyvmomi: RebootGuest()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="reboot_guest(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="standby_guest",
        name="Standby Guest OS",
        description="Put the guest OS into standby/sleep mode. Requires VMware Tools. pyvmomi: StandbyGuest()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="standby_guest(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="suspend_vm",
        name="Suspend Virtual Machine",
        description="Suspend a running VM, saving its state to disk. pyvmomi: SuspendVM_Task()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="suspend_vm(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="reset_vm",
        name="Reset Virtual Machine",
        description="Hard reset a VM (like pressing reset button). pyvmomi: ResetVM_Task()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="reset_vm(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="mark_as_template",
        name="Convert VM to Template",
        description="Convert a virtual machine to a template. VM must be powered off. pyvmomi: MarkAsTemplate()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM to convert",
            },
        ],
        example="mark_as_template(vm_name='golden-image')",
    ),
    OperationDefinition(
        operation_id="mark_as_virtual_machine",
        name="Convert Template to VM",
        description="Convert a template back to a virtual machine. pyvmomi: MarkAsVirtualMachine(pool, host)",
        category="compute",
        parameters=[
            {
                "name": "template_name",
                "type": "string",
                "required": True,
                "description": "Name of the template",
            },
            {
                "name": "resource_pool",
                "type": "string",
                "required": False,
                "description": "Target resource pool",
            },
            {
                "name": "host_name",
                "type": "string",
                "required": False,
                "description": "Target host",
            },
        ],
        example="mark_as_virtual_machine(template_name='golden-image')",
    ),
    OperationDefinition(
        operation_id="upgrade_virtual_hardware",
        name="Upgrade VM Hardware Version",
        description="Upgrade VM to latest virtual hardware version. VM must be powered off. pyvmomi: UpgradeVM_Task(version)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "version",
                "type": "string",
                "required": False,
                "description": "Target hardware version (e.g., 'vmx-19'). Default: latest",
            },
        ],
        example="upgrade_virtual_hardware(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="mount_tools_installer",
        name="Mount VMware Tools Installer",
        description="Mount the VMware Tools installer CD in the VM. pyvmomi: MountToolsInstaller()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="mount_tools_installer(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="unmount_tools_installer",
        name="Unmount VMware Tools Installer",
        description="Unmount the VMware Tools installer CD from the VM. pyvmomi: UnmountToolsInstaller()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="unmount_tools_installer(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="upgrade_tools",
        name="Upgrade VMware Tools",
        description="Upgrade VMware Tools in the guest OS. pyvmomi: UpgradeTools_Task(installerOptions)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "installer_options",
                "type": "string",
                "required": False,
                "description": "Installer command line options",
            },
        ],
        example="upgrade_tools(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="export_vm",
        name="Export VM as OVF",
        description="Export a VM to OVF format. Returns an HTTP NFC lease for downloading. pyvmomi: ExportVm()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="export_vm(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="unregister_vm",
        name="Unregister VM from Inventory",
        description="Remove VM from vCenter inventory without deleting files. pyvmomi: UnregisterVM()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="unregister_vm(vm_name='old-vm')",
    ),
    OperationDefinition(
        operation_id="destroy_vm",
        name="Destroy Virtual Machine",
        description="Delete a VM and all its files. DESTRUCTIVE OPERATION. pyvmomi: Destroy_Task()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM to destroy",
            },
        ],
        example="destroy_vm(vm_name='test-vm')",
    ),
    OperationDefinition(
        operation_id="answer_vm_question",
        name="Answer VM Question",
        description="Answer a question that is blocking VM operations. pyvmomi: AnswerVM(questionId, answerChoice)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "question_id",
                "type": "string",
                "required": True,
                "description": "ID of the question to answer",
            },
            {
                "name": "answer_choice",
                "type": "string",
                "required": True,
                "description": "Answer choice (e.g., 'button.uuid.movedTheVM')",
            },
        ],
        example="answer_vm_question(vm_name='web-01', question_id='0', answer_choice='button.uuid.movedTheVM')",
    ),
    OperationDefinition(
        operation_id="acquire_mks_ticket",
        name="Acquire VM Console Ticket",
        description="Get a ticket for VM console access (MKS/WMKS). pyvmomi: AcquireMksTicket()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="acquire_mks_ticket(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="acquire_ticket",
        name="Acquire VM Ticket",
        description="Get a ticket for VM access (console, VNC, etc). pyvmomi: AcquireTicket(ticketType)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "ticket_type",
                "type": "string",
                "required": True,
                "description": "Ticket type: mks, device, guestControl, webmks",
            },
        ],
        example="acquire_ticket(vm_name='web-01', ticket_type='webmks')",
    ),
    OperationDefinition(
        operation_id="reboot_host",
        name="Reboot ESXi Host",
        description="Reboot an ESXi host. Host should be in maintenance mode. pyvmomi: RebootHost_Task(force)",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "force",
                "type": "boolean",
                "required": False,
                "description": "Force reboot even if VMs running (default: False)",
            },
        ],
        example="reboot_host(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="shutdown_host",
        name="Shutdown ESXi Host",
        description="Shutdown an ESXi host. Host should be in maintenance mode. pyvmomi: ShutdownHost_Task(force)",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "force",
                "type": "boolean",
                "required": False,
                "description": "Force shutdown even if VMs running (default: False)",
            },
        ],
        example="shutdown_host(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="disconnect_host",
        name="Disconnect Host from vCenter",
        description="Disconnect an ESXi host from vCenter Server. pyvmomi: DisconnectHost_Task()",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
        ],
        example="disconnect_host(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="reconnect_host",
        name="Reconnect Host to vCenter",
        description="Reconnect a disconnected ESXi host to vCenter. pyvmomi: ReconnectHost_Task(cnxSpec, reconnectSpec)",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "username",
                "type": "string",
                "required": False,
                "description": "ESXi root username",
            },
            {
                "name": "password",
                "type": "string",
                "required": False,
                "description": "ESXi root password",
            },
        ],
        example="reconnect_host(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="enter_lockdown_mode",
        name="Enter Lockdown Mode",
        description="Put host into lockdown mode, restricting direct access. pyvmomi: EnterLockdownMode()",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
        ],
        example="enter_lockdown_mode(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="exit_lockdown_mode",
        name="Exit Lockdown Mode",
        description="Take host out of lockdown mode, allowing direct access. pyvmomi: ExitLockdownMode()",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
        ],
        example="exit_lockdown_mode(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="enter_standby_mode",
        name="Enter Standby Mode (Power Down)",
        description="Put host into standby mode to save power. VMs must be evacuated. pyvmomi: PowerDownHostToStandBy_Task()",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "timeout",
                "type": "integer",
                "required": False,
                "description": "Timeout in seconds",
            },
            {
                "name": "evacuate_vms",
                "type": "boolean",
                "required": False,
                "description": "Evacuate powered-off VMs (default: True)",
            },
        ],
        example="enter_standby_mode(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="exit_standby_mode",
        name="Exit Standby Mode (Power Up)",
        description="Wake up host from standby mode. pyvmomi: PowerUpHostFromStandBy_Task()",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "timeout",
                "type": "integer",
                "required": False,
                "description": "Timeout in seconds",
            },
        ],
        example="exit_standby_mode(host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="cancel_drs_recommendation",
        name="Cancel DRS Recommendation",
        description="Cancel/dismiss a DRS recommendation. pyvmomi: CancelRecommendation(key)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
            {
                "name": "recommendation_key",
                "type": "string",
                "required": True,
                "description": "Recommendation key to cancel",
            },
        ],
        example="cancel_drs_recommendation(cluster_name='Production', recommendation_key='rec-1')",
    ),
    OperationDefinition(
        operation_id="refresh_drs_recommendations",
        name="Refresh DRS Recommendations",
        description="Force refresh of DRS recommendations for a cluster. pyvmomi: RefreshRecommendation()",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
        ],
        example="refresh_drs_recommendations(cluster_name='Production')",
    ),
    OperationDefinition(
        operation_id="find_rules_for_vm",
        name="Find DRS Rules for VM",
        description="Find all DRS rules that apply to a specific VM. pyvmomi: FindRulesForVm(vm)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
            {"name": "vm_name", "type": "string", "required": True, "description": "Name of VM"},
        ],
        example="find_rules_for_vm(cluster_name='Production', vm_name='web-01')",
        response_entity_type="DRSRule",
        response_identifier_field="key",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="recommend_hosts_for_vm",
        name="Recommend Hosts for VM",
        description="Get host recommendations for placing a VM. pyvmomi: RecommendHostsForVm(vm, pool)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
            {"name": "vm_name", "type": "string", "required": True, "description": "Name of VM"},
        ],
        example="recommend_hosts_for_vm(cluster_name='Production', vm_name='web-01')",
        response_entity_type="HostRecommendation",
        response_identifier_field="host",
        response_display_name_field="host",
    ),
    OperationDefinition(
        operation_id="add_host_to_cluster",
        name="Add Host to Cluster",
        description="Add a standalone host to a cluster. pyvmomi: AddHost_Task(spec, asConnected, resourcePool, license)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Hostname or IP of ESXi host",
            },
            {
                "name": "username",
                "type": "string",
                "required": True,
                "description": "ESXi root username",
            },
            {
                "name": "password",
                "type": "string",
                "required": True,
                "description": "ESXi root password",
            },
            {
                "name": "as_connected",
                "type": "boolean",
                "required": False,
                "description": "Connect host after adding (default: True)",
            },
        ],
        example="add_host_to_cluster(cluster_name='Production', host_name='esxi-new.example.com', username='root', password='...')",
    ),
    OperationDefinition(
        operation_id="move_host_into_cluster",
        name="Move Host into Cluster",
        description="Move an existing host into a cluster. pyvmomi: MoveHostInto_Task(host, resourcePool)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Target cluster name",
            },
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of host to move",
            },
        ],
        example="move_host_into_cluster(cluster_name='Production', host_name='esxi-01.example.com')",
    ),
    OperationDefinition(
        operation_id="create_resource_pool",
        name="Create Resource Pool",
        description="Create a new resource pool. pyvmomi: CreateResourcePool(name, spec)",
        category="compute",
        parameters=[
            {
                "name": "parent_pool",
                "type": "string",
                "required": True,
                "description": "Parent resource pool name",
            },
            {
                "name": "pool_name",
                "type": "string",
                "required": True,
                "description": "Name for new resource pool",
            },
            {
                "name": "cpu_reservation",
                "type": "integer",
                "required": False,
                "description": "CPU reservation in MHz",
            },
            {
                "name": "memory_reservation_mb",
                "type": "integer",
                "required": False,
                "description": "Memory reservation in MB",
            },
        ],
        example="create_resource_pool(parent_pool='Resources', pool_name='Dev-Pool')",
    ),
    OperationDefinition(
        operation_id="destroy_resource_pool",
        name="Delete Resource Pool",
        description="Delete a resource pool. VMs will be moved to parent. pyvmomi: Destroy_Task()",
        category="compute",
        parameters=[
            {
                "name": "pool_name",
                "type": "string",
                "required": True,
                "description": "Name of resource pool to delete",
            },
        ],
        example="destroy_resource_pool(pool_name='old-pool')",
    ),
    OperationDefinition(
        operation_id="update_resource_pool",
        name="Update Resource Pool Config",
        description="Update resource pool CPU and memory configuration. pyvmomi: UpdateConfig(name, spec)",
        category="compute",
        parameters=[
            {
                "name": "pool_name",
                "type": "string",
                "required": True,
                "description": "Name of resource pool",
            },
            {
                "name": "cpu_reservation",
                "type": "integer",
                "required": False,
                "description": "CPU reservation in MHz",
            },
            {
                "name": "cpu_limit",
                "type": "integer",
                "required": False,
                "description": "CPU limit in MHz (-1 for unlimited)",
            },
            {
                "name": "memory_reservation_mb",
                "type": "integer",
                "required": False,
                "description": "Memory reservation in MB",
            },
            {
                "name": "memory_limit_mb",
                "type": "integer",
                "required": False,
                "description": "Memory limit in MB (-1 for unlimited)",
            },
        ],
        example="update_resource_pool(pool_name='Dev-Pool', cpu_reservation=2000)",
    ),
    OperationDefinition(
        operation_id="customize_guest",
        name="Customize Guest OS",
        description="Apply customization spec to VM (hostname, IP, domain join). pyvmomi: CustomizeVM_Task(spec)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "hostname",
                "type": "string",
                "required": False,
                "description": "New hostname for VM",
            },
            {
                "name": "domain",
                "type": "string",
                "required": False,
                "description": "Domain to join",
            },
            {
                "name": "ip_address",
                "type": "string",
                "required": False,
                "description": "Static IP address",
            },
            {
                "name": "subnet_mask",
                "type": "string",
                "required": False,
                "description": "Subnet mask",
            },
            {
                "name": "gateway",
                "type": "string",
                "required": False,
                "description": "Default gateway",
            },
            {
                "name": "dns_servers",
                "type": "string",
                "required": False,
                "description": "Comma-separated DNS servers",
            },
        ],
        example="customize_guest(vm_name='web-01', hostname='web-server-01', ip_address='10.0.0.100')",
    ),
    OperationDefinition(
        operation_id="create_screenshot",
        name="Create VM Screenshot",
        description="Create a screenshot of the VM's display. pyvmomi: CreateScreenshot_Task()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="create_screenshot(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="set_boot_options",
        name="Set VM Boot Options",
        description="Configure VM boot order and options.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "boot_delay",
                "type": "integer",
                "required": False,
                "description": "Boot delay in milliseconds",
            },
            {
                "name": "enter_bios_setup",
                "type": "boolean",
                "required": False,
                "description": "Enter BIOS on next boot",
            },
            {
                "name": "boot_retry_enabled",
                "type": "boolean",
                "required": False,
                "description": "Enable boot retry",
            },
            {
                "name": "boot_retry_delay",
                "type": "integer",
                "required": False,
                "description": "Boot retry delay in milliseconds",
            },
        ],
        example="set_boot_options(vm_name='web-01', boot_delay=5000, enter_bios_setup=True)",
    ),
    OperationDefinition(
        operation_id="instant_clone",
        name="Instant Clone VM",
        description="Create an instant clone of a running VM. Very fast cloning. pyvmomi: InstantClone_Task(spec)",
        category="compute",
        parameters=[
            {
                "name": "source_vm",
                "type": "string",
                "required": True,
                "description": "Name of source VM (must be running)",
            },
            {
                "name": "clone_name",
                "type": "string",
                "required": True,
                "description": "Name for the instant clone",
            },
            {
                "name": "target_folder",
                "type": "string",
                "required": False,
                "description": "Target folder name",
            },
        ],
        example="instant_clone(source_vm='template-vm', clone_name='instant-clone-01')",
    ),
    OperationDefinition(
        operation_id="reload_vm",
        name="Reload VM Configuration",
        description="Reload VM configuration from datastore. pyvmomi: ReloadVirtualMachineFromPath_Task(configurationPath)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="reload_vm(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="terminate_fault_tolerance",
        name="Turn Off Fault Tolerance",
        description="Disable Fault Tolerance for a VM. pyvmomi: TurnOffFaultToleranceForVM_Task()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="terminate_fault_tolerance(vm_name='critical-vm')",
    ),
    OperationDefinition(
        operation_id="send_nmi",
        name="Send NMI to VM",
        description="Send Non-Maskable Interrupt to VM. Used for debugging. pyvmomi: SendNMI()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="send_nmi(vm_name='debug-vm')",
    ),
    OperationDefinition(
        operation_id="update_host_flags",
        name="Update Host Flags",
        description="Update host flags (lockdown mode settings). pyvmomi: UpdateFlags(flagInfo)",
        category="compute",
        parameters=[
            {
                "name": "host_name",
                "type": "string",
                "required": True,
                "description": "Name of ESXi host",
            },
            {
                "name": "enable_management",
                "type": "boolean",
                "required": False,
                "description": "Enable management services",
            },
        ],
        example="update_host_flags(host_name='esxi-01.example.com', enable_management=True)",
    ),
    OperationDefinition(
        operation_id="reconfigure_cluster",
        name="Reconfigure Cluster",
        description="Reconfigure cluster settings (DRS, HA, etc). pyvmomi: ReconfigureCluster_Task(spec, modify)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
            {
                "name": "drs_enabled",
                "type": "boolean",
                "required": False,
                "description": "Enable/disable DRS",
            },
            {
                "name": "drs_automation_level",
                "type": "string",
                "required": False,
                "description": "DRS level: manual, partiallyAutomated, fullyAutomated",
            },
            {
                "name": "ha_enabled",
                "type": "boolean",
                "required": False,
                "description": "Enable/disable HA",
            },
            {
                "name": "ha_host_monitoring",
                "type": "string",
                "required": False,
                "description": "Host monitoring: enabled, disabled",
            },
        ],
        example="reconfigure_cluster(cluster_name='Production', drs_enabled=True, drs_automation_level='fullyAutomated')",
    ),
    OperationDefinition(
        operation_id="cluster_enter_maintenance_mode",
        name="Cluster Enter Maintenance Mode",
        description="Put entire cluster into maintenance mode. pyvmomi: ClusterEnterMaintenanceMode()",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
        ],
        example="cluster_enter_maintenance_mode(cluster_name='Production')",
    ),
    OperationDefinition(
        operation_id="place_vm",
        name="Place VM (Compute Recommendation)",
        description="Get placement recommendations for a VM. pyvmomi: PlaceVm(placementSpec)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of VM to place",
            },
        ],
        example="place_vm(cluster_name='Production', vm_name='new-vm')",
    ),
    OperationDefinition(
        operation_id="destroy_cluster",
        name="Destroy Cluster",
        description="Delete a cluster. Hosts must be removed first. pyvmomi: Destroy_Task()",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster to destroy",
            },
        ],
        example="destroy_cluster(cluster_name='old-cluster')",
    ),
    OperationDefinition(
        operation_id="rename_cluster",
        name="Rename Cluster",
        description="Rename a cluster. pyvmomi: Rename_Task(newName)",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Current cluster name",
            },
            {
                "name": "new_name",
                "type": "string",
                "required": True,
                "description": "New cluster name",
            },
        ],
        example="rename_cluster(cluster_name='old-name', new_name='Production-Cluster')",
    ),
    OperationDefinition(
        operation_id="get_evc_mode",
        name="Get EVC Mode",
        description="Get Enhanced vMotion Compatibility mode for cluster.",
        category="compute",
        parameters=[
            {
                "name": "cluster_name",
                "type": "string",
                "required": True,
                "description": "Name of cluster",
            },
        ],
        example="get_evc_mode(cluster_name='Production')",
    ),
    OperationDefinition(
        operation_id="create_vm",
        name="Create Virtual Machine",
        description="Create a new virtual machine from scratch.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name for the new VM",
            },
            {
                "name": "num_cpus",
                "type": "integer",
                "required": True,
                "description": "Number of vCPUs",
            },
            {
                "name": "memory_mb",
                "type": "integer",
                "required": True,
                "description": "Memory in MB",
            },
            {
                "name": "disk_size_gb",
                "type": "integer",
                "required": True,
                "description": "Primary disk size in GB",
            },
            {
                "name": "guest_os_id",
                "type": "string",
                "required": True,
                "description": "Guest OS ID (e.g., 'ubuntu64Guest', 'windows9Server64Guest')",
            },
            {
                "name": "datastore_name",
                "type": "string",
                "required": True,
                "description": "Target datastore",
            },
            {
                "name": "folder_name",
                "type": "string",
                "required": False,
                "description": "Target folder",
            },
            {
                "name": "resource_pool",
                "type": "string",
                "required": False,
                "description": "Target resource pool",
            },
            {
                "name": "network_name",
                "type": "string",
                "required": False,
                "description": "Network to connect to",
            },
        ],
        example="create_vm(vm_name='new-vm', num_cpus=2, memory_mb=4096, disk_size_gb=40, guest_os_id='ubuntu64Guest', datastore_name='datastore1')",
    ),
    OperationDefinition(
        operation_id="deploy_ovf",
        name="Deploy OVF/OVA Template",
        description="Deploy a VM from an OVF or OVA file.",
        category="compute",
        parameters=[
            {
                "name": "ovf_url",
                "type": "string",
                "required": True,
                "description": "URL or datastore path to OVF/OVA",
            },
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name for the new VM",
            },
            {
                "name": "datastore_name",
                "type": "string",
                "required": True,
                "description": "Target datastore",
            },
            {
                "name": "folder_name",
                "type": "string",
                "required": False,
                "description": "Target folder",
            },
            {
                "name": "resource_pool",
                "type": "string",
                "required": False,
                "description": "Target resource pool",
            },
            {
                "name": "network_mappings",
                "type": "string",
                "required": False,
                "description": 'Network mappings (JSON: {"OVF Network": "VM Network"})',
            },
        ],
        example="deploy_ovf(ovf_url='https://example.com/template.ova', vm_name='deployed-vm', datastore_name='datastore1')",
    ),
    OperationDefinition(
        operation_id="get_vm_guest_info",
        name="Get VM Guest Info",
        description="Get detailed guest OS information including IP, hostname, guest tools.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="get_vm_guest_info(vm_name='web-01')",
        response_entity_type="GuestInfo",
        response_identifier_field="ip_address",
        response_display_name_field="host_name",
    ),
    OperationDefinition(
        operation_id="list_guest_processes",
        name="List Guest Processes",
        description="List running processes inside guest OS. Requires VMware Tools.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "username",
                "type": "string",
                "required": True,
                "description": "Guest OS username",
            },
            {
                "name": "password",
                "type": "string",
                "required": True,
                "description": "Guest OS password",
            },
        ],
        example="list_guest_processes(vm_name='web-01', username='admin', password='...')",
        response_entity_type="Process",
        response_identifier_field="pid",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="run_program_in_guest",
        name="Run Program in Guest",
        description="Execute a program inside guest OS. Requires VMware Tools.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "username",
                "type": "string",
                "required": True,
                "description": "Guest OS username",
            },
            {
                "name": "password",
                "type": "string",
                "required": True,
                "description": "Guest OS password",
            },
            {
                "name": "program_path",
                "type": "string",
                "required": True,
                "description": "Full path to program",
            },
            {
                "name": "arguments",
                "type": "string",
                "required": False,
                "description": "Program arguments",
            },
            {
                "name": "working_directory",
                "type": "string",
                "required": False,
                "description": "Working directory",
            },
        ],
        example="run_program_in_guest(vm_name='web-01', username='admin', password='...', program_path='/usr/bin/ls', arguments='-la')",
    ),
    OperationDefinition(
        operation_id="upload_file_to_guest",
        name="Upload File to Guest",
        description="Upload a file to the guest OS. Requires VMware Tools.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "username",
                "type": "string",
                "required": True,
                "description": "Guest OS username",
            },
            {
                "name": "password",
                "type": "string",
                "required": True,
                "description": "Guest OS password",
            },
            {
                "name": "guest_path",
                "type": "string",
                "required": True,
                "description": "Destination path in guest",
            },
            {
                "name": "file_content",
                "type": "string",
                "required": True,
                "description": "File content (base64 for binary)",
            },
            {
                "name": "overwrite",
                "type": "boolean",
                "required": False,
                "description": "Overwrite if exists (default: True)",
            },
        ],
        example="upload_file_to_guest(vm_name='web-01', username='admin', password='...', guest_path='/tmp/test.txt', file_content='Hello World')",
    ),
    OperationDefinition(
        operation_id="download_file_from_guest",
        name="Download File from Guest",
        description="Download a file from the guest OS. Requires VMware Tools.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "username",
                "type": "string",
                "required": True,
                "description": "Guest OS username",
            },
            {
                "name": "password",
                "type": "string",
                "required": True,
                "description": "Guest OS password",
            },
            {
                "name": "guest_path",
                "type": "string",
                "required": True,
                "description": "Path to file in guest",
            },
        ],
        example="download_file_from_guest(vm_name='web-01', username='admin', password='...', guest_path='/var/log/app.log')",
    ),
    OperationDefinition(
        operation_id="create_directory_in_guest",
        name="Create Directory in Guest",
        description="Create a directory inside guest OS. Requires VMware Tools.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "username",
                "type": "string",
                "required": True,
                "description": "Guest OS username",
            },
            {
                "name": "password",
                "type": "string",
                "required": True,
                "description": "Guest OS password",
            },
            {
                "name": "directory_path",
                "type": "string",
                "required": True,
                "description": "Directory path to create",
            },
            {
                "name": "create_parents",
                "type": "boolean",
                "required": False,
                "description": "Create parent directories (default: True)",
            },
        ],
        example="create_directory_in_guest(vm_name='web-01', username='admin', password='...', directory_path='/opt/myapp')",
    ),
    OperationDefinition(
        operation_id="delete_file_in_guest",
        name="Delete File in Guest",
        description="Delete a file from guest OS. Requires VMware Tools.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "username",
                "type": "string",
                "required": True,
                "description": "Guest OS username",
            },
            {
                "name": "password",
                "type": "string",
                "required": True,
                "description": "Guest OS password",
            },
            {
                "name": "file_path",
                "type": "string",
                "required": True,
                "description": "Path to file to delete",
            },
        ],
        example="delete_file_in_guest(vm_name='web-01', username='admin', password='...', file_path='/tmp/old-file.txt')",
    ),
    OperationDefinition(
        operation_id="set_custom_value",
        name="Set Custom Attribute Value",
        description="Set a custom attribute value on a VM. pyvmomi: SetCustomValue(key, value)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "attribute_key",
                "type": "string",
                "required": True,
                "description": "Custom attribute key",
            },
            {
                "name": "attribute_value",
                "type": "string",
                "required": True,
                "description": "Custom attribute value",
            },
        ],
        example="set_custom_value(vm_name='web-01', attribute_key='Environment', attribute_value='Production')",
    ),
    OperationDefinition(
        operation_id="get_custom_values",
        name="Get Custom Attribute Values",
        description="Get all custom attribute values for a VM.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="get_custom_values(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="set_screen_resolution",
        name="Set VM Screen Resolution",
        description="Set the screen resolution for a VM. pyvmomi: SetScreenResolution(width, height)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "width",
                "type": "integer",
                "required": True,
                "description": "Screen width in pixels",
            },
            {
                "name": "height",
                "type": "integer",
                "required": True,
                "description": "Screen height in pixels",
            },
        ],
        example="set_screen_resolution(vm_name='vdi-01', width=1920, height=1080)",
    ),
    OperationDefinition(
        operation_id="deploy_library_item",
        name="Deploy VM from Content Library",
        description="Deploy a VM from a content library template.",
        category="compute",
        parameters=[
            {
                "name": "library_name",
                "type": "string",
                "required": True,
                "description": "Name of content library",
            },
            {
                "name": "item_name",
                "type": "string",
                "required": True,
                "description": "Name of library item",
            },
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name for new VM",
            },
            {
                "name": "datastore_name",
                "type": "string",
                "required": True,
                "description": "Target datastore",
            },
            {
                "name": "folder_name",
                "type": "string",
                "required": False,
                "description": "Target folder",
            },
            {
                "name": "resource_pool",
                "type": "string",
                "required": False,
                "description": "Target resource pool",
            },
        ],
        example="deploy_library_item(library_name='Templates', item_name='ubuntu-template', vm_name='new-vm', datastore_name='datastore1')",
    ),
    OperationDefinition(
        operation_id="get_vm_tags",
        name="Get VM Tags",
        description="Get all tags assigned to a VM.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="get_vm_tags(vm_name='web-01')",
        response_entity_type="Tag",
        response_identifier_field="id",
        response_display_name_field="name",
    ),
    OperationDefinition(
        operation_id="assign_tag_to_vm",
        name="Assign Tag to VM",
        description="Assign a tag to a VM.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "tag_name",
                "type": "string",
                "required": True,
                "description": "Name of tag to assign",
            },
        ],
        example="assign_tag_to_vm(vm_name='web-01', tag_name='Production')",
    ),
    OperationDefinition(
        operation_id="remove_tag_from_vm",
        name="Remove Tag from VM",
        description="Remove a tag from a VM.",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "tag_name",
                "type": "string",
                "required": True,
                "description": "Name of tag to remove",
            },
        ],
        example="remove_tag_from_vm(vm_name='web-01', tag_name='Development')",
    ),
    OperationDefinition(
        operation_id="revert_to_current_snapshot",
        name="Revert to Current Snapshot",
        description="Revert VM to its most recent snapshot. pyvmomi: RevertToCurrentSnapshot_Task(host, suppressPowerOn)",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
            {
                "name": "suppress_power_on",
                "type": "boolean",
                "required": False,
                "description": "Prevent power on after revert (default: False)",
            },
        ],
        example="revert_to_current_snapshot(vm_name='web-01')",
    ),
    OperationDefinition(
        operation_id="reset_guest_information",
        name="Reset Guest Information",
        description="Reset guest information to default. pyvmomi: ResetGuestInformation()",
        category="compute",
        parameters=[
            {
                "name": "vm_name",
                "type": "string",
                "required": True,
                "description": "Name of the VM",
            },
        ],
        example="reset_guest_information(vm_name='web-01')",
    ),
]
