"""
Data Reduction Engine Implementation.

This module implements the server-side query execution that processes
large API responses into LLM-ready reduced datasets.

Key Design Decisions:
1. Use pandas for data processing (mature, fast, well-tested)
2. Safe expression evaluation (no exec/eval)
3. Graceful error handling with partial results
4. Comprehensive logging for debugging
"""

from __future__ import annotations

import logging
import re
import time
from typing import Any, Optional

import pandas as pd

from meho_agent.data_reduction.query_schema import (
    AggregateFunction,
    AggregateSpec,
    ComputeField,
    DataQuery,
    FilterCondition,
    FilterGroup,
    FilterOperator,
    ReducedData,
    SortSpec,
)

logger = logging.getLogger(__name__)


class DataReductionError(Exception):
    """Error during data reduction."""
    pass


class DataReductionEngine:
    """
    Executes DataQuery specifications against API response data.
    
    This is the core component that enables LLMs to work with large
    datasets by processing them server-side and returning only the
    relevant, reduced results.
    
    Example:
        ```python
        engine = DataReductionEngine()
        
        # API response with 500 clusters
        api_response = {"clusters": [...]}  # Large response
        
        # Query generated by LLM
        query = DataQuery(
            source_path="clusters",
            select=["name", "memory_pct"],
            filter=FilterGroup(conditions=[
                FilterCondition(field="memory_pct", operator=">", value=80)
            ]),
            sort=SortSpec(field="memory_pct", direction="desc"),
            limit=10
        )
        
        # Execute - returns only 10 high-memory clusters
        result = engine.execute(api_response, query)
        # result.records = 10 items, ~1KB instead of 2MB
        ```
    """
    
    def __init__(
        self,
        max_records: int = 10000,
        max_output_records: int = 1000,
    ):
        """
        Initialize the engine.
        
        Args:
            max_records: Maximum records to process (safety limit)
            max_output_records: Maximum records to return
        """
        self.max_records = max_records
        self.max_output_records = max_output_records
    
    def execute(
        self,
        data: dict[str, Any],
        query: DataQuery,
    ) -> ReducedData:
        """
        Execute a query against the data.
        
        Args:
            data: The raw API response data
            query: The query specification
            
        Returns:
            ReducedData with processed results
        """
        start_time = time.perf_counter()
        
        try:
            # Step 1: Extract source data
            records = self._extract_source(data, query.source_path)
            total_source = len(records)
            logger.debug(f"Extracted {total_source} records from source_path='{query.source_path}'")
            
            # Safety limit
            if total_source > self.max_records:
                logger.warning(
                    f"Source has {total_source} records, truncating to {self.max_records}"
                )
                records = records[:self.max_records]
            
            # Convert to DataFrame for processing
            df = pd.DataFrame(records)
            
            if df.empty:
                return self._empty_result(query, start_time, total_source)
            
            # Step 2: Select fields (if specified)
            if query.select:
                df = self._select_fields(df, query.select)
            
            # Step 3: Compute derived fields
            for compute in query.compute:
                df = self._compute_field(df, compute)
            
            # Step 4: Apply filters
            if query.filter:
                df = self._apply_filter(df, query.filter)
            
            total_after_filter = len(df)
            logger.debug(f"After filtering: {total_after_filter} records")
            
            # Step 5: Compute aggregates (before limit)
            aggregates = {}
            if query.aggregates:
                aggregates = self._compute_aggregates(df, query.aggregates, query.group_by)
            
            # Step 6: Sort
            if query.sort:
                df = self._apply_sort(df, query.sort)
            
            # Step 7: Apply offset/limit
            if query.offset:
                df = df.iloc[query.offset:]
            
            limit = min(
                query.limit or self.max_output_records,
                self.max_output_records
            )
            df = df.head(limit)
            
            # Convert back to records
            output_records = df.to_dict("records")
            
            processing_time = (time.perf_counter() - start_time) * 1000
            
            return ReducedData(
                records=output_records,
                total_source_records=total_source,
                total_after_filter=total_after_filter,
                returned_records=len(output_records),
                aggregates=aggregates,
                query_applied=query,
                processing_time_ms=processing_time,
            )
            
        except Exception as e:
            logger.exception(f"Data reduction failed: {e}")
            raise DataReductionError(f"Query execution failed: {e}") from e
    
    def _extract_source(
        self,
        data: dict[str, Any],
        source_path: str,
    ) -> list[dict[str, Any]]:
        """Extract records from the source path."""
        if not source_path:
            # Root level
            if isinstance(data, list):
                return list(data)
            elif isinstance(data, dict):
                # Try common patterns
                for key in ["data", "items", "results", "records"]:
                    if key in data and isinstance(data[key], list):
                        return list(data[key])
                # Return dict as single record
                return [dict(data)]
            return []
        
        # Navigate the path
        current = data
        parts = source_path.replace("[*]", "").split(".")
        
        for part in parts:
            if not part:
                continue
            if isinstance(current, dict):
                current = current.get(part, [])
            elif isinstance(current, list) and current:
                # Try to extract from first item or flatten
                current = [item.get(part, {}) for item in current if isinstance(item, dict)]
            else:
                return []
        
        if isinstance(current, list):
            return current
        elif isinstance(current, dict):
            return [current]
        return []
    
    def _select_fields(
        self,
        df: pd.DataFrame,
        fields: list[str],
    ) -> pd.DataFrame:
        """Select specific fields from the DataFrame."""
        # Handle nested field access
        available_cols = set(df.columns)
        selected = []
        
        for field in fields:
            if field in available_cols:
                selected.append(field)
            elif "." in field:
                # Nested field - try to expand
                base, rest = field.split(".", 1)
                if base in available_cols:
                    # Extract nested value
                    df[field] = df[base].apply(
                        lambda x: self._get_nested(x, rest) if isinstance(x, dict) else None
                    )
                    selected.append(field)
            else:
                logger.warning(f"Field '{field}' not found in data")
        
        if selected:
            return df[selected]
        return df
    
    def _get_nested(self, obj: Any, path: str) -> Any:
        """Get nested value from object."""
        current = obj
        for part in path.split("."):
            if isinstance(current, dict):
                current = current.get(part)
            else:
                return None
        return current
    
    def _compute_field(
        self,
        df: pd.DataFrame,
        compute: ComputeField,
    ) -> pd.DataFrame:
        """Compute a derived field."""
        try:
            # Use pandas eval for safe expression evaluation
            # This supports basic arithmetic and field references
            df[compute.name] = df.eval(compute.expression)
        except Exception as e:
            logger.warning(f"Failed to compute field '{compute.name}': {e}")
            df[compute.name] = None
        return df
    
    def _apply_filter(
        self,
        df: pd.DataFrame,
        filter_group: FilterGroup,
    ) -> pd.DataFrame:
        """Apply filter conditions to the DataFrame."""
        mask = self._evaluate_filter_group(df, filter_group)
        return df[mask] if mask is not None else df
    
    def _evaluate_filter_group(
        self,
        df: pd.DataFrame,
        group: FilterGroup,
    ) -> Optional[pd.Series]:
        """Evaluate a filter group to a boolean mask."""
        masks = []
        
        for condition in group.conditions:
            if isinstance(condition, FilterGroup):
                mask = self._evaluate_filter_group(df, condition)
            else:
                mask = self._evaluate_condition(df, condition)
            
            if mask is not None:
                masks.append(mask)
        
        if not masks:
            return None
        
        if group.logic == "and":
            result = masks[0]
            for m in masks[1:]:
                result = result & m
            return result
        else:  # "or"
            result = masks[0]
            for m in masks[1:]:
                result = result | m
            return result
    
    def _evaluate_condition(
        self,
        df: pd.DataFrame,
        condition: FilterCondition,
    ) -> Optional[pd.Series]:
        """Evaluate a single filter condition."""
        field = condition.field
        
        # Handle nested fields
        if "." in field and field not in df.columns:
            base, rest = field.split(".", 1)
            if base in df.columns:
                series = df[base].apply(
                    lambda x: self._get_nested(x, rest) if isinstance(x, dict) else None
                )
            else:
                logger.warning(f"Filter field '{field}' not found")
                return None
        elif field in df.columns:
            series = df[field]
        else:
            logger.warning(f"Filter field '{field}' not found")
            return None
        
        op = condition.operator
        value = condition.value
        
        try:
            if op == FilterOperator.EQ:
                return series == value
            elif op == FilterOperator.NE:
                return series != value
            elif op == FilterOperator.GT:
                return series > value
            elif op == FilterOperator.GTE:
                return series >= value
            elif op == FilterOperator.LT:
                return series < value
            elif op == FilterOperator.LTE:
                return series <= value
            elif op == FilterOperator.CONTAINS:
                return series.astype(str).str.contains(str(value), case=False, na=False)
            elif op == FilterOperator.STARTS_WITH:
                return series.astype(str).str.startswith(str(value), na=False)
            elif op == FilterOperator.ENDS_WITH:
                return series.astype(str).str.endswith(str(value), na=False)
            elif op == FilterOperator.MATCHES:
                return series.astype(str).str.match(str(value), na=False)
            elif op == FilterOperator.IN:
                return series.isin(value if isinstance(value, list) else [value])
            elif op == FilterOperator.NOT_IN:
                return ~series.isin(value if isinstance(value, list) else [value])
            elif op == FilterOperator.IS_NULL:
                return series.isna()
            elif op == FilterOperator.IS_NOT_NULL:
                return series.notna()
            else:
                logger.warning(f"Unknown operator: {op}")
                return None
        except Exception as e:
            logger.warning(f"Filter evaluation failed: {e}")
            return None
    
    def _apply_sort(
        self,
        df: pd.DataFrame,
        sort: SortSpec,
    ) -> pd.DataFrame:
        """Apply sorting to the DataFrame."""
        if sort.field in df.columns:
            return df.sort_values(
                by=sort.field,
                ascending=(sort.direction == "asc"),
                na_position="last"
            )
        else:
            logger.warning(f"Sort field '{sort.field}' not found")
            return df
    
    def _compute_aggregates(
        self,
        df: pd.DataFrame,
        aggregates: list[AggregateSpec],
        group_by: Optional[list[str]] = None,
    ) -> dict[str, Any]:
        """Compute aggregate values."""
        results = {}
        
        # If grouping, handle separately
        if group_by:
            valid_group_by = [g for g in group_by if g in df.columns]
            if valid_group_by:
                grouped = df.groupby(valid_group_by)
                for agg in aggregates:
                    agg_result = self._compute_single_aggregate(grouped, agg)
                    # Convert to dict if it's a Series/DataFrame, otherwise use as-is
                    if hasattr(agg_result, 'to_dict'):
                        results[agg.name] = agg_result.to_dict()
                    else:
                        results[agg.name] = agg_result
                return results
        
        # No grouping - compute over entire DataFrame
        for agg in aggregates:
            results[agg.name] = self._compute_single_aggregate(df, agg)
        
        return results
    
    def _compute_single_aggregate(
        self,
        df_or_group: pd.DataFrame,
        agg: AggregateSpec,
    ) -> Any:
        """Compute a single aggregate value."""
        func = agg.function
        field = agg.field
        
        try:
            if field == "*":
                # Count all rows
                if func == AggregateFunction.COUNT:
                    # For DataFrame, use len(); for GroupBy, use ngroups or size()
                    if isinstance(df_or_group, pd.DataFrame):
                        return len(df_or_group)
                    else:
                        # GroupBy object
                        return df_or_group.ngroups
                return None
            
            # Check if field exists
            if isinstance(df_or_group, pd.DataFrame):
                if field not in df_or_group.columns:
                    logger.warning(f"Aggregate field '{field}' not found")
                    return None
                series = df_or_group[field]
            else:
                # GroupBy - get the field from the grouped data
                series = df_or_group[field]
            
            if func == AggregateFunction.COUNT:
                result = series.count()
                return int(result) if isinstance(result, (int, float)) else result
            elif func == AggregateFunction.SUM:
                result = series.sum()
                return float(result) if isinstance(result, (int, float)) else result
            elif func == AggregateFunction.AVG:
                result = series.mean()
                return float(result) if isinstance(result, (int, float)) else result
            elif func == AggregateFunction.MIN:
                val = series.min()
                if isinstance(val, (int, float)):
                    return float(val) if pd.notna(val) else None
                return val
            elif func == AggregateFunction.MAX:
                val = series.max()
                if isinstance(val, (int, float)):
                    return float(val) if pd.notna(val) else None
                return val
            elif func == AggregateFunction.FIRST:
                if isinstance(df_or_group, pd.DataFrame):
                    return series.iloc[0] if len(series) > 0 else None
                return series.first()
            elif func == AggregateFunction.LAST:
                if isinstance(df_or_group, pd.DataFrame):
                    return series.iloc[-1] if len(series) > 0 else None
                return series.last()
            elif func == AggregateFunction.MEDIAN:
                result = series.median()
                return float(result) if isinstance(result, (int, float)) else result
            elif func == AggregateFunction.STD:
                result = series.std()
                return float(result) if isinstance(result, (int, float)) else result
            elif func == AggregateFunction.VAR:
                result = series.var()
                return float(result) if isinstance(result, (int, float)) else result
            elif func == AggregateFunction.COLLECT:
                if isinstance(df_or_group, pd.DataFrame):
                    return series.tolist()
                return series.apply(list)
            elif func == AggregateFunction.DISTINCT:
                if isinstance(df_or_group, pd.DataFrame):
                    return series.unique().tolist()
                return series.apply(lambda x: list(set(x)))
            else:
                logger.warning(f"Unknown aggregate function: {func}")
                return None
                
        except Exception as e:
            logger.warning(f"Aggregate computation failed: {e}")
            return None
    
    def _empty_result(
        self,
        query: DataQuery,
        start_time: float,
        total_source: int,
    ) -> ReducedData:
        """Create an empty result."""
        return ReducedData(
            records=[],
            total_source_records=total_source,
            total_after_filter=0,
            returned_records=0,
            aggregates={},
            query_applied=query,
            processing_time_ms=(time.perf_counter() - start_time) * 1000,
        )


