# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 evoila Group

"""Typed-op metadata + registrar for :class:`InstallerConnector`.

The Installer's governed bring-up surface ships as four submit/poll typed
primitives (``source_kind="typed"``, #3078) so they dispatch on a fresh boot
with zero catalog ingest:

* ``installer.sddc.spec.validate`` — submit an ``SddcSpec`` validation
  dry-run (``POST /v1/sddcs/validations``; ``caution``).
* ``installer.sddc.validation.status`` — poll one validation
  (``GET /v1/sddcs/validations/{id}``; ``safe``).
* ``installer.sddc.bringup.start`` — start the bring-up (``POST /v1/sddcs``;
  ``dangerous`` + ``requires_approval``).
* ``installer.sddc.bringup.status`` — poll one bring-up task
  (``GET /v1/sddcs/{id}``; ``safe``).

The vendor bring-up API is natively asynchronous — every submit returns its
tracking object in seconds and progress rides the status polls — so each
primitive is a short call and the standard park → approve → resume machinery
governs ``bringup.start`` unmodified. Op bodies live in
:mod:`meho_backplane.connectors.vcf_installer.typed_reads` /
:mod:`.typed_writes`; a thin bound-method shim on :class:`InstallerConnector`
exposes each under its ``handler_attr`` name so the dispatcher's
``import_handler`` walk recovers the callable.

The one-shot governed bring-up (validate → deploy in a single approved unit)
remains the separate ``installer.composite.sddc.bringup`` composite in
:mod:`.bringup`. The dataclass + tuple + registrar shape mirrors
:mod:`meho_backplane.connectors.sddc_manager.typed_ops`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Literal

import structlog

from meho_backplane.connectors.vcf_installer.typed_writes import (
    INSTALLER_BRINGUP_START_OP_ID,
    INSTALLER_SPEC_VALIDATE_OP_ID,
)

if TYPE_CHECKING:
    from meho_backplane.retrieval.embedding import EmbeddingService

__all__ = [
    "INSTALLER_TYPED_OPS",
    "INSTALLER_TYPED_WHEN_TO_USE_BY_GROUP",
    "InstallerTypedOp",
    "register_installer_typed_operations",
]

_log = structlog.get_logger(__name__)

_GROUP_BRINGUP = "installer-bringup"


@dataclass(frozen=True)
class InstallerTypedOp:
    """Metadata for one Installer typed op registered at lifespan startup.

    Fields mirror the keyword arguments
    :func:`~meho_backplane.operations.typed_register.register_typed_operation`
    accepts. ``handler_attr`` is the attribute name on
    :class:`~meho_backplane.connectors.vcf_installer.connector.InstallerConnector`
    exposing the async handler. Mirrors
    :class:`~meho_backplane.connectors.sddc_manager.typed_ops.SddcTypedOp`.
    """

    op_id: str
    handler_attr: str
    summary: str
    description: str
    parameter_schema: dict[str, Any]
    response_schema: dict[str, Any] | None
    group_key: str | None
    tags: tuple[str, ...]
    safety_level: Literal["safe", "caution", "dangerous"]
    requires_approval: bool
    llm_instructions: dict[str, Any] | None


#: Curated ``when_to_use`` blurb per typed-op group.
INSTALLER_TYPED_WHEN_TO_USE_BY_GROUP: dict[str, str] = {
    _GROUP_BRINGUP: (
        "Use to run or track a VCF management-domain bring-up on the Installer "
        "appliance via short submit/poll primitives: installer.sddc.spec.validate "
        "submits an SddcSpec dry-run and installer.sddc.validation.status polls "
        "its verdict; installer.sddc.bringup.start (dangerous, approval-gated) "
        "starts the bring-up and installer.sddc.bringup.status polls the task's "
        "lifecycle state (IN_PROGRESS / COMPLETED_WITH_SUCCESS / "
        "COMPLETED_WITH_FAILURE) and per-stage sub-tasks. The one-shot governed "
        "validate-then-deploy unit is installer.composite.sddc.bringup."
    ),
}


def _instructions(
    *, when_to_use: str, output_shape: str, parameter_hints: dict[str, str]
) -> dict[str, Any]:
    return {
        "when_to_use": when_to_use,
        "output_shape": output_shape,
        "parameter_hints": parameter_hints,
    }


def _sddc_spec_parameter_schema(posted_to: str) -> dict[str, Any]:
    """The shared ``{"spec": <SddcSpec>}`` parameter schema of the two submits."""
    return {
        "type": "object",
        "properties": {
            "spec": {
                "type": "object",
                "description": (
                    "The full VCF Installer SddcSpec body (as generated by the "
                    f"deploy-automation factory from a resolved EnvSpec); POSTed "
                    f"verbatim to {posted_to}."
                ),
                "additionalProperties": True,
            },
        },
        "required": ["spec"],
        "additionalProperties": False,
    }


_SPEC_VALIDATE = InstallerTypedOp(
    op_id=INSTALLER_SPEC_VALIDATE_OP_ID,
    handler_attr="sddc_spec_validate",
    summary="Submit an SddcSpec for a non-mutating validation dry-run.",
    description=(
        "Submits the SddcSpec to POST /v1/sddcs/validations — the Installer's "
        "non-mutating dry-run — and returns the vendor Validation object the "
        "moment the submit is accepted (typically executionStatus=IN_PROGRESS "
        "with the id to poll). Poll installer.sddc.validation.status to the "
        "terminal executionStatus and read the resultStatus verdict "
        "(SUCCEEDED / WARNING / FAILED) plus per-check detail. Writes to the "
        "installer appliance but mutates no estate. safety_level=caution."
    ),
    parameter_schema=_sddc_spec_parameter_schema("/v1/sddcs/validations"),
    response_schema={"type": "object", "additionalProperties": True},
    group_key=_GROUP_BRINGUP,
    tags=("vcf", "installer", "bringup", "validation", "write"),
    safety_level="caution",
    requires_approval=False,
    llm_instructions=_instructions(
        when_to_use=(
            "Call with a full SddcSpec to dry-run-validate it on the Installer "
            "before any bring-up is started. Nothing is deployed."
        ),
        output_shape=(
            "{id, executionStatus, resultStatus, validationChecks: [...]}. "
            "Keep the id and poll installer.sddc.validation.status until "
            "executionStatus is terminal."
        ),
        parameter_hints={"spec": "The full SddcSpec object, POSTed verbatim."},
    ),
)

_VALIDATION_STATUS = InstallerTypedOp(
    op_id="installer.sddc.validation.status",
    handler_attr="sddc_validation_status",
    summary="Status of one SddcSpec validation dry-run.",
    description=(
        "Reads one spec validation via GET /v1/sddcs/validations/{id} — the "
        "Validation object whose executionStatus carries the IN_PROGRESS / "
        "COMPLETED lifecycle, resultStatus the SUCCEEDED / WARNING / FAILED "
        "verdict, and validationChecks[] the per-check detail. Requires the "
        "validation id returned by installer.sddc.spec.validate. Works with "
        "zero catalog ingest. safety_level=safe, read-only."
    ),
    parameter_schema={
        "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "minLength": 1,
                "description": "The validation id returned by installer.sddc.spec.validate.",
            },
        },
        "required": ["id"],
        "additionalProperties": False,
    },
    response_schema={"type": "object", "additionalProperties": True},
    group_key=_GROUP_BRINGUP,
    tags=("read-only", "vcf", "installer", "bringup", "validation", "status"),
    safety_level="safe",
    requires_approval=False,
    llm_instructions=_instructions(
        when_to_use=(
            "Call with a validation id to check whether an SddcSpec dry-run "
            "has finished and whether it passed."
        ),
        output_shape=(
            "{id, executionStatus, resultStatus, validationChecks: [...]}. "
            "Terminal when executionStatus leaves IN_PROGRESS; surface any "
            "FAILED check."
        ),
        parameter_hints={"id": "The validation id from installer.sddc.spec.validate."},
    ),
)

_BRINGUP_START = InstallerTypedOp(
    op_id=INSTALLER_BRINGUP_START_OP_ID,
    handler_attr="sddc_bringup_start",
    summary="Start a VCF management-domain bring-up from an SddcSpec.",
    description=(
        "Submits the SddcSpec to POST /v1/sddcs — the estate mutation — and "
        "returns the vendor SddcTask the moment the deploy is accepted "
        "(typically within seconds). The bring-up itself runs for hours on "
        "the appliance; poll installer.sddc.bringup.status with the returned "
        "id to a terminal state. dangerous + requires_approval — the dispatch "
        "parks for approval first and the approver sees an SDDC "
        "identity/network preview, never passwords. Run "
        "installer.sddc.spec.validate to a SUCCEEDED/WARNING verdict first — "
        "this primitive submits the spec as-is."
    ),
    parameter_schema=_sddc_spec_parameter_schema("/v1/sddcs"),
    response_schema={"type": "object", "additionalProperties": True},
    group_key=_GROUP_BRINGUP,
    tags=("vcf", "installer", "bringup", "deploy", "dangerous"),
    safety_level="dangerous",
    requires_approval=True,
    llm_instructions=_instructions(
        when_to_use=(
            "Call with a validated SddcSpec to start the management-domain "
            "bring-up. Parks for human approval before anything runs."
        ),
        output_shape=(
            "{id, name, status, vcfInstanceName, ...} (SddcTask). Keep the id "
            "and poll installer.sddc.bringup.status to terminal."
        ),
        parameter_hints={"spec": "The full SddcSpec object, POSTed verbatim."},
    ),
)

_BRINGUP_STATUS = InstallerTypedOp(
    op_id="installer.sddc.bringup.status",
    handler_attr="sddc_bringup_status",
    summary="Lifecycle status of one VCF bring-up task.",
    description=(
        "Reads one VCF management-domain bring-up task via GET /v1/sddcs/{id} — "
        "the SddcTask object whose top-level status carries the "
        "IN_PROGRESS / COMPLETED_WITH_SUCCESS / COMPLETED_WITH_FAILURE lifecycle "
        "state, plus sddcSubTasks[] and milestones[] for per-stage progress. "
        "Requires the bring-up id returned by installer.sddc.bringup.start (or "
        "the governed composite). The poll an operator (or the automation "
        "add-on) runs while a bring-up is in flight or to triage a failed one. "
        "Works with zero catalog ingest. safety_level=safe, read-only."
    ),
    parameter_schema={
        "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "minLength": 1,
                "description": "The bring-up (SDDC) task id returned by the deploy.",
            },
        },
        "required": ["id"],
        "additionalProperties": False,
    },
    response_schema={"type": "object", "additionalProperties": True},
    group_key=_GROUP_BRINGUP,
    tags=("read-only", "vcf", "installer", "bringup", "status"),
    safety_level="safe",
    requires_approval=False,
    llm_instructions=_instructions(
        when_to_use=(
            "Call with a bring-up id to check whether a VCF management-domain "
            "deployment has completed, is still running, or failed."
        ),
        output_shape=(
            "{id, name, status, vcfInstanceName, sddcSubTasks: [...], "
            "milestones: [...]}. Surface the top-level status and any failed "
            "sub-task."
        ),
        parameter_hints={"id": "The bring-up (SDDC) task id from the deploy."},
    ),
)


#: The typed ops :class:`InstallerConnector` registers at lifespan startup,
#: in submit → poll order per primitive pair.
INSTALLER_TYPED_OPS: tuple[InstallerTypedOp, ...] = (
    _SPEC_VALIDATE,
    _VALIDATION_STATUS,
    _BRINGUP_START,
    _BRINGUP_STATUS,
)


async def register_installer_typed_operations(
    *,
    embedding_service: EmbeddingService | None = None,
) -> None:
    """Upsert every op in :data:`INSTALLER_TYPED_OPS` into ``endpoint_descriptor``.

    Queued onto the lifespan-driven registrar list via
    :func:`~meho_backplane.operations.typed_register.register_typed_op_registrar`
    in this package's ``__init__``. Mirrors
    :func:`~meho_backplane.connectors.sddc_manager.typed_ops.register_sddc_typed_operations`.
    """
    from meho_backplane.connectors.vcf_installer.connector import InstallerConnector
    from meho_backplane.operations.typed_register import register_typed_operation

    for op in INSTALLER_TYPED_OPS:
        handler = getattr(InstallerConnector, op.handler_attr, None)
        if handler is None:
            raise AttributeError(
                f"InstallerConnector typed op {op.op_id!r} declares "
                f"handler_attr={op.handler_attr!r} but the class has no such attribute"
            )
        when_to_use = (
            None if op.group_key is None else INSTALLER_TYPED_WHEN_TO_USE_BY_GROUP.get(op.group_key)
        )
        if op.group_key is not None and when_to_use is None:
            raise ValueError(
                f"InstallerConnector typed op {op.op_id!r} declares "
                f"group_key={op.group_key!r} but no curated when_to_use exists for that key."
            )
        await register_typed_operation(
            product=InstallerConnector.product,
            version=InstallerConnector.version,
            impl_id=InstallerConnector.impl_id,
            op_id=op.op_id,
            handler=handler,
            summary=op.summary,
            description=op.description,
            parameter_schema=op.parameter_schema,
            response_schema=op.response_schema,
            group_key=op.group_key,
            when_to_use=when_to_use,
            tags=list(op.tags),
            safety_level=op.safety_level,
            requires_approval=op.requires_approval,
            llm_instructions=op.llm_instructions,
            embedding_service=embedding_service,
        )
    _log.info(
        "installer_typed_operations_registered",
        count=len(INSTALLER_TYPED_OPS),
        product=InstallerConnector.product,
        version=InstallerConnector.version,
        impl_id=InstallerConnector.impl_id,
    )
