"""Squashed initial schema for knowledge.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create knowledge module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM knowledge_chunk LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # Enable pgvector extension for vector similarity search
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ==========================================================================
    # knowledge_chunk - Vector-searchable knowledge with ACL
    # Final state: connector-scoped, three-tier scoping, 1024D Voyage AI embeddings,
    # timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE knowledge_chunk (
            id UUID PRIMARY KEY,
            tenant_id VARCHAR,
            user_id VARCHAR,
            roles JSONB NOT NULL DEFAULT '[]',
            groups JSONB NOT NULL DEFAULT '[]',
            text TEXT NOT NULL,
            tags JSONB NOT NULL DEFAULT '[]',
            source_uri TEXT,
            search_metadata JSONB DEFAULT '{}',
            expires_at TIMESTAMP WITH TIME ZONE,
            knowledge_type VARCHAR(50) NOT NULL DEFAULT 'documentation',
            priority INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            connector_id UUID REFERENCES connector(id) ON DELETE CASCADE,
            scope_type VARCHAR(20) NOT NULL DEFAULT 'instance',
            connector_type_scope VARCHAR(50),
            embedding vector(1024),
            CONSTRAINT ck_knowledge_chunk_scope_connector CHECK (
                (scope_type = 'instance' AND connector_id IS NOT NULL) OR
                (scope_type IN ('global', 'type') AND connector_id IS NULL)
            )
        )
    """)

    # Scalar indexes
    op.execute("CREATE INDEX ix_knowledge_chunk_tenant_id ON knowledge_chunk (tenant_id)")
    op.execute("CREATE INDEX ix_knowledge_chunk_user_id ON knowledge_chunk (user_id)")
    op.execute("CREATE INDEX idx_knowledge_expires_at ON knowledge_chunk (expires_at)")
    op.execute("CREATE INDEX idx_knowledge_type ON knowledge_chunk (knowledge_type)")
    op.execute(
        "CREATE INDEX idx_knowledge_type_expires ON knowledge_chunk (knowledge_type, expires_at)"
    )

    # Connector-scoped indexes
    op.execute("CREATE INDEX ix_knowledge_chunk_connector ON knowledge_chunk (connector_id)")
    op.execute(
        "CREATE INDEX ix_knowledge_chunk_tenant_connector "
        "ON knowledge_chunk (tenant_id, connector_id)"
    )
    op.execute(
        "CREATE INDEX ix_knowledge_chunk_tenant_user ON knowledge_chunk (tenant_id, user_id)"
    )

    # Three-tier scope indexes
    op.execute(
        "CREATE INDEX ix_knowledge_chunk_scope ON knowledge_chunk (tenant_id, scope_type)"
    )
    op.execute(
        "CREATE INDEX ix_knowledge_chunk_type_scope "
        "ON knowledge_chunk (tenant_id, connector_type_scope) "
        "WHERE scope_type = 'type'"
    )

    # HNSW index for fast vector similarity search (1024D Voyage AI)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_embedding_hnsw
        ON knowledge_chunk
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # Full-text search index
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_text_fts
        ON knowledge_chunk
        USING gin (to_tsvector('english', text))
    """)

    # ==========================================================================
    # ingestion_jobs - Document ingestion tracking
    # Final state: with connector_id FK, timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE ingestion_jobs (
            id UUID PRIMARY KEY,
            job_type VARCHAR(50) NOT NULL,
            status VARCHAR(50) NOT NULL DEFAULT 'pending',
            tenant_id VARCHAR NOT NULL,
            filename VARCHAR(255),
            file_size INTEGER,
            knowledge_type VARCHAR(50),
            tags JSONB NOT NULL DEFAULT '[]',
            total_chunks INTEGER,
            chunks_processed INTEGER NOT NULL DEFAULT 0,
            chunks_created INTEGER NOT NULL DEFAULT 0,
            current_stage VARCHAR(50),
            stage_progress FLOAT DEFAULT 0.0,
            overall_progress FLOAT DEFAULT 0.0,
            status_message TEXT,
            stage_started_at TIMESTAMP WITH TIME ZONE,
            estimated_completion TIMESTAMP WITH TIME ZONE,
            error_stage VARCHAR(50),
            error_chunk_index INTEGER,
            error_details JSONB,
            error TEXT,
            retention_until TIMESTAMP WITH TIME ZONE,
            chunk_ids JSONB,
            started_at TIMESTAMP WITH TIME ZONE,
            completed_at TIMESTAMP WITH TIME ZONE,
            connector_id UUID REFERENCES connector(id) ON DELETE CASCADE
        )
    """)

    # Indexes
    op.execute("CREATE INDEX idx_ingestion_jobs_status ON ingestion_jobs (status)")
    op.execute("CREATE INDEX idx_ingestion_jobs_tenant ON ingestion_jobs (tenant_id)")
    op.execute(
        "CREATE INDEX idx_ingestion_jobs_tenant_status ON ingestion_jobs (tenant_id, status)"
    )
    op.execute("CREATE INDEX idx_ingestion_jobs_retention ON ingestion_jobs (retention_until)")


def downgrade() -> None:
    """Drop knowledge module tables."""
    op.execute("DROP TABLE IF EXISTS ingestion_jobs CASCADE")
    op.execute("DROP TABLE IF EXISTS knowledge_chunk CASCADE")
