"""Squashed initial schema for topology.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create topology module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM topology_entities LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # Ensure pgvector extension exists (shared with knowledge module)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ==========================================================================
    # topology_entities - Discovered system entities
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE topology_entities (
            id UUID PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            connector_id UUID,
            connector_name VARCHAR(255),
            entity_type VARCHAR(100) NOT NULL,
            connector_type VARCHAR(50) NOT NULL,
            scope JSONB DEFAULT '{}',
            canonical_id VARCHAR(500) NOT NULL,
            description TEXT NOT NULL,
            raw_attributes JSONB DEFAULT '{}',
            discovered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_verified_at TIMESTAMP WITH TIME ZONE,
            stale_at TIMESTAMP WITH TIME ZONE,
            tenant_id VARCHAR(100) NOT NULL
        )
    """)

    # Indexes for topology_entities
    op.execute("CREATE INDEX idx_topology_entities_tenant ON topology_entities (tenant_id)")
    op.execute("CREATE INDEX idx_topology_entities_connector ON topology_entities (connector_id)")
    op.execute("CREATE INDEX idx_topology_entities_name ON topology_entities (name)")
    op.execute("CREATE INDEX idx_topology_entities_type ON topology_entities (entity_type)")
    op.execute(
        "CREATE INDEX idx_topology_entities_connector_type ON topology_entities (connector_type)"
    )
    # Unique identity
    op.execute(
        "CREATE UNIQUE INDEX idx_topology_entity_identity "
        "ON topology_entities (tenant_id, connector_id, entity_type, canonical_id)"
    )

    # ==========================================================================
    # topology_embeddings - Vector embeddings for entities
    # Final state: 1024D Voyage AI embeddings
    # ==========================================================================
    op.execute("""
        CREATE TABLE topology_embeddings (
            entity_id UUID PRIMARY KEY REFERENCES topology_entities(id) ON DELETE CASCADE,
            embedding vector(1024)
        )
    """)

    # HNSW index for fast vector similarity search
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_topology_embeddings_hnsw
        ON topology_embeddings
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # ==========================================================================
    # topology_relationships - Relationships between entities
    # Final state: timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE topology_relationships (
            id UUID PRIMARY KEY,
            from_entity_id UUID NOT NULL REFERENCES topology_entities(id) ON DELETE CASCADE,
            to_entity_id UUID NOT NULL REFERENCES topology_entities(id) ON DELETE CASCADE,
            relationship_type VARCHAR(100) NOT NULL,
            discovered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_verified_at TIMESTAMP WITH TIME ZONE
        )
    """)

    # Indexes for topology_relationships
    op.execute(
        "CREATE INDEX idx_topology_relationships_from "
        "ON topology_relationships (from_entity_id)"
    )
    op.execute(
        "CREATE INDEX idx_topology_relationships_to ON topology_relationships (to_entity_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_topology_relationships_unique "
        "ON topology_relationships (from_entity_id, to_entity_id, relationship_type)"
    )

    # ==========================================================================
    # topology_same_as - Cross-connector entity correlations
    # Final state: with tenant_id, timezone-aware timestamps
    # ==========================================================================
    op.execute("""
        CREATE TABLE topology_same_as (
            id UUID PRIMARY KEY,
            entity_a_id UUID NOT NULL REFERENCES topology_entities(id) ON DELETE CASCADE,
            entity_b_id UUID NOT NULL REFERENCES topology_entities(id) ON DELETE CASCADE,
            similarity_score FLOAT NOT NULL,
            verified_via TEXT[] NOT NULL,
            discovered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_verified_at TIMESTAMP WITH TIME ZONE,
            tenant_id VARCHAR(100) NOT NULL
        )
    """)

    # Indexes for topology_same_as
    op.execute("CREATE INDEX idx_topology_same_as_tenant ON topology_same_as (tenant_id)")
    op.execute(
        "CREATE UNIQUE INDEX idx_topology_same_as_unique "
        "ON topology_same_as (entity_a_id, entity_b_id, tenant_id)"
    )

    # ==========================================================================
    # topology_same_as_suggestion - Pending correlation suggestions
    # ==========================================================================
    op.execute("""
        CREATE TABLE topology_same_as_suggestion (
            id UUID PRIMARY KEY,
            entity_a_id UUID NOT NULL REFERENCES topology_entities(id) ON DELETE CASCADE,
            entity_b_id UUID NOT NULL REFERENCES topology_entities(id) ON DELETE CASCADE,
            confidence FLOAT NOT NULL,
            match_type VARCHAR(50) NOT NULL,
            match_details TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            suggested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            resolved_at TIMESTAMP WITH TIME ZONE,
            resolved_by VARCHAR(255),
            llm_verification_attempted BOOLEAN NOT NULL DEFAULT false,
            llm_verification_result JSONB,
            tenant_id VARCHAR(100) NOT NULL
        )
    """)

    # Indexes for topology_same_as_suggestion
    op.execute(
        "CREATE INDEX idx_topology_suggestion_tenant ON topology_same_as_suggestion (tenant_id)"
    )
    op.execute(
        "CREATE INDEX idx_topology_suggestion_status ON topology_same_as_suggestion (status)"
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_topology_suggestion_unique "
        "ON topology_same_as_suggestion (entity_a_id, entity_b_id)"
    )


def downgrade() -> None:
    """Drop topology module tables."""
    op.execute("DROP TABLE IF EXISTS topology_same_as_suggestion CASCADE")
    op.execute("DROP TABLE IF EXISTS topology_same_as CASCADE")
    op.execute("DROP TABLE IF EXISTS topology_relationships CASCADE")
    op.execute("DROP TABLE IF EXISTS topology_embeddings CASCADE")
    op.execute("DROP TABLE IF EXISTS topology_entities CASCADE")
