"""Squashed initial schema for orchestrator_skills.

Replaces all previous migrations with a single consolidated DDL.
Generated by reading all migration files and constructing the final schema state.
For existing deployments: run `alembic stamp squash_001` instead of upgrade.

Revision ID: squash_001
Revises: None
Create Date: 2026-03-26
"""

import sqlalchemy as sa
from alembic import op

revision = "squash_001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create orchestrator_skills module tables (squashed)."""
    conn = op.get_bind()
    try:
        conn.execute(sa.text("SELECT 1 FROM orchestrator_skill LIMIT 1"))
        return  # Existing deployment -- skip DDL
    except Exception:
        pass  # Fresh install -- run DDL below

    # ==========================================================================
    # orchestrator_skill - Cross-system reasoning skills with LLM summaries
    # Final state: with skill_type, connector_type, is_customized,
    # updated unique constraint (tenant_id, name, skill_type)
    # ==========================================================================
    op.execute("""
        CREATE TABLE orchestrator_skill (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id VARCHAR NOT NULL,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            content TEXT NOT NULL,
            summary TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            is_customized BOOLEAN NOT NULL DEFAULT false,
            skill_type VARCHAR(50) NOT NULL DEFAULT 'orchestrator',
            connector_type VARCHAR(50)
        )
    """)
    op.execute("CREATE INDEX ix_orch_skill_tenant ON orchestrator_skill (tenant_id)")
    op.execute(
        "ALTER TABLE orchestrator_skill "
        "ADD CONSTRAINT uq_orch_skill_tenant_name_type "
        "UNIQUE (tenant_id, name, skill_type)"
    )
    op.execute(
        "CREATE INDEX ix_orch_skill_connector_type "
        "ON orchestrator_skill (tenant_id, skill_type, connector_type)"
    )


def downgrade() -> None:
    """Drop orchestrator_skills module tables."""
    op.execute("DROP TABLE IF EXISTS orchestrator_skill CASCADE")
