# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 evoila Group

"""Filesystem-path helpers for the UI chassis.

Two deploy shapes have to resolve the same template / static tree:

1. **Image / wheel deploy.** ``meho_backplane`` is installed into a
   site-packages tree; ``ui/templates/`` and ``ui/static/`` ship as
   package data because :mod:`meho_backplane.ui` is included in the
   ``[tool.hatch.build.targets.wheel].packages`` glob. Resolving the
   directory from the package's ``__file__`` works in this shape
   (zip-imported wheels are not in scope -- the Docker image installs
   uncompressed).

2. **Source-tree dev deploy.** ``uvicorn --reload`` runs from
   ``backend/`` with ``src/`` on ``PYTHONPATH``; the same ``__file__``
   relative resolution lands on the in-repo tree, which is what local
   ``tailwindcss --watch`` writes into.

Both shapes converge on ``Path(__file__).resolve().parent / "<sub>"``;
no ``importlib.resources`` indirection is required because the UI
module is never zip-imported (the backplane image installs the wheel
uncompressed; ``alembic/`` next door does the same thing without
``importlib.resources``).

The functions are deliberately tiny and synchronous: every UI route
calls ``templates_dir()`` at most once per process (the Jinja2
``Environment`` caches the load), and ``static_dist_dir()`` is read by
the FastAPI ``StaticFiles`` mount once at startup (T5 #866).
"""

from pathlib import Path

_UI_PACKAGE_ROOT = Path(__file__).resolve().parent


def templates_dir() -> Path:
    """Return the absolute path of the Jinja2 templates directory.

    The directory always exists at this path because it ships in the
    package tree (Task #863 created it). Callers should treat a missing
    directory as a packaging bug, not a runtime condition.
    """
    return _UI_PACKAGE_ROOT / "templates"


def static_src_dir() -> Path:
    """Return the absolute path of the Tailwind input + vendored JS tree.

    This is the *input* to the Tailwind CLI build step; the *output*
    (compiled CSS) lives in :func:`static_dist_dir`. Vendored JS files
    (``htmx.min.js``, ``alpine.min.js``, ``cytoscape.min.js``) live
    under ``static/src/vendor/`` and are served directly from this
    tree -- they are not regenerated by the Tailwind build.
    """
    return _UI_PACKAGE_ROOT / "static" / "src"


def static_dist_dir() -> Path:
    """Return the absolute path of the compiled-asset directory.

    ``static/dist/`` is gitignored; it materializes in two places:

    * In the Docker image, written by the ``tailwindcss`` CLI step in
      ``backend/Dockerfile`` against ``static/src/styles.css``.
    * In local dev, written by ``tailwindcss --watch`` running
      alongside ``uvicorn --reload``.

    The directory may not exist on first ``uvicorn`` start in a fresh
    clone; T5 (#866) calls :func:`ensure_static_dist_dir` from the
    FastAPI lifespan startup so the :class:`StaticFiles` mount does
    not crash on construction.
    """
    return _UI_PACKAGE_ROOT / "static" / "dist"


def static_root_dir() -> Path:
    """Return the absolute path of the ``static/`` directory tree.

    The single mount point T5 (#866) registers at ``/ui/static`` covers
    *both* the vendored source tree (``static/src/vendor/*.js``) and
    the compiled Tailwind output (``static/dist/tailwind.css``). One
    mount keeps the URL shape ``/ui/static/{src,dist}/...`` consistent
    with the references the chassis ``base.html`` already emits, while
    avoiding a second :class:`StaticFiles` instance (each mount carries
    its own ``check_dir`` constructor cost).
    """
    return _UI_PACKAGE_ROOT / "static"


def ensure_static_dist_dir() -> Path:
    """Create the ``static/dist/`` directory if missing, return its path.

    Called from the FastAPI lifespan startup so the chassis
    :class:`~starlette.staticfiles.StaticFiles` mount can subtree the
    ``static/`` parent on a fresh clone where ``tailwindcss --watch``
    has not yet materialised the directory. The mount succeeds; a
    request for ``/ui/static/dist/tailwind.css`` returns 404 until the
    Tailwind build writes the file, which is the documented behaviour
    in ``docs/codebase/ui.md`` -- a missing compiled stylesheet is an
    operator-facing remediation, not a chassis crash.

    Idempotent: ``mkdir(parents=True, exist_ok=True)`` so repeat lifespan
    starts (a uvicorn reload cycle) are no-ops.
    """
    dist = static_dist_dir()
    dist.mkdir(parents=True, exist_ok=True)
    return dist
