# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 evoila Group

"""Filesystem-path helpers for the UI chassis.

Two deploy shapes have to resolve the same template / static tree:

1. **Image / wheel deploy.** ``meho_backplane`` is installed into a
   site-packages tree; ``ui/templates/`` and ``ui/static/`` ship as
   package data because :mod:`meho_backplane.ui` is included in the
   ``[tool.hatch.build.targets.wheel].packages`` glob. Resolving the
   directory from the package's ``__file__`` works in this shape
   (zip-imported wheels are not in scope -- the Docker image installs
   uncompressed).

2. **Source-tree dev deploy.** ``uvicorn --reload`` runs from
   ``backend/`` with ``src/`` on ``PYTHONPATH``; the same ``__file__``
   relative resolution lands on the in-repo tree, which is what local
   ``tailwindcss --watch`` writes into.

Both shapes converge on ``Path(__file__).resolve().parent / "<sub>"``;
no ``importlib.resources`` indirection is required because the UI
module is never zip-imported (the backplane image installs the wheel
uncompressed; ``alembic/`` next door does the same thing without
``importlib.resources``).

The functions are deliberately tiny and synchronous: every UI route
calls ``templates_dir()`` at most once per process (the Jinja2
``Environment`` caches the load), and ``static_dist_dir()`` is read by
the FastAPI ``StaticFiles`` mount once at startup (T5 #866).
"""

from pathlib import Path

_UI_PACKAGE_ROOT = Path(__file__).resolve().parent


def templates_dir() -> Path:
    """Return the absolute path of the Jinja2 templates directory.

    The directory always exists at this path because it ships in the
    package tree (Task #863 created it). Callers should treat a missing
    directory as a packaging bug, not a runtime condition.
    """
    return _UI_PACKAGE_ROOT / "templates"


def static_src_dir() -> Path:
    """Return the absolute path of the Tailwind input + vendored JS tree.

    This is the *input* to the Tailwind CLI build step; the *output*
    (compiled CSS) lives in :func:`static_dist_dir`. Vendored JS files
    (``htmx.min.js``, ``alpine.min.js``, ``cytoscape.min.js``) live
    under ``static/src/vendor/`` and are served directly from this
    tree -- they are not regenerated by the Tailwind build.
    """
    return _UI_PACKAGE_ROOT / "static" / "src"


def static_dist_dir() -> Path:
    """Return the absolute path of the compiled-asset directory.

    ``static/dist/`` is gitignored; it materializes in two places:

    * In the Docker image, written by the ``tailwindcss`` CLI step in
      ``backend/Dockerfile`` against ``static/src/styles.css``.
    * In local dev, written by ``tailwindcss --watch`` running
      alongside ``uvicorn --reload``.

    The directory may not exist on first ``uvicorn`` start in a fresh
    clone; T5 #866's startup hook surfaces the operator-facing remediation
    (``run tailwindcss once``). For chassis-only use (this Task) the
    directory is constructed but unused.
    """
    return _UI_PACKAGE_ROOT / "static" / "dist"
